// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using LLMPulse.SDK.Client;
using LLMPulse.SDK.Logging;
using LLMPulse.SDK.Model;
using System.Diagnostics.CodeAnalysis;

namespace LLMPulse.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IAIAgentTrafficApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        AIAgentTrafficApiEvents Events { get; }

        /// <summary>
        /// AI bot crawler traffic (Scale plan or above, Beta)
        /// </summary>
        /// <remarks>
        /// Aggregated AI bot traffic hitting the project&#39;s origin server (GPTBot, PerplexityBot, ClaudeBot, OAI-SearchBot, Google-Extended, etc.). Sourced from Cloudflare or CSV uploads. Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="range">Number of days to look back (alternative to from/to) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="bot">Filter by bot slug (e.g. gptbot, claudebot, perplexitybot) (optional)</param>
        /// <param name="company">Filter by company (e.g. openai, anthropic, google) (optional)</param>
        /// <param name="groupBy"> (optional, default to bot)</param>
        /// <param name="granularity"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetAgentTrafficApiResponse"/>&gt;</returns>
        Task<IGetAgentTrafficApiResponse> GetAgentTrafficAsync(int projectId, Option<int> range = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<string> bot = default, Option<string> company = default, Option<string> groupBy = default, Option<string> granularity = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// AI bot crawler traffic (Scale plan or above, Beta)
        /// </summary>
        /// <remarks>
        /// Aggregated AI bot traffic hitting the project&#39;s origin server (GPTBot, PerplexityBot, ClaudeBot, OAI-SearchBot, Google-Extended, etc.). Sourced from Cloudflare or CSV uploads. Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED.
        /// </remarks>
        /// <param name="projectId">Project ID</param>
        /// <param name="range">Number of days to look back (alternative to from/to) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="bot">Filter by bot slug (e.g. gptbot, claudebot, perplexitybot) (optional)</param>
        /// <param name="company">Filter by company (e.g. openai, anthropic, google) (optional)</param>
        /// <param name="groupBy"> (optional, default to bot)</param>
        /// <param name="granularity"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetAgentTrafficApiResponse"/>?&gt;</returns>
        Task<IGetAgentTrafficApiResponse?> GetAgentTrafficOrDefaultAsync(int projectId, Option<int> range = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<string> bot = default, Option<string> company = default, Option<string> groupBy = default, Option<string> granularity = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// AI referral traffic (Scale plan or above)
        /// </summary>
        /// <remarks>
        /// AI referral traffic for a project: human visits arriving from AI assistants (ChatGPT, Perplexity, Gemini, Claude, etc.), measured from the connected web analytics provider (Google Analytics 4, Adobe Analytics, PostHog, Plausible or Piano). Returns per-source users, sessions and conversions with totals and a conversion rate. Requires a connected provider and the Scale plan; otherwise returns ERR_AI_TRAFFIC_NOT_CONNECTED or ERR_PLAN_REQUIRED.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="range">Number of days to look back (alternative to from/to) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="source">Filter by a single AI source slug (e.g. chatgpt, perplexity, gemini, claude) (optional)</param>
        /// <param name="granularity"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetAiTrafficApiResponse"/>&gt;</returns>
        Task<IGetAiTrafficApiResponse> GetAiTrafficAsync(int projectId, Option<int> range = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<string> source = default, Option<string> granularity = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// AI referral traffic (Scale plan or above)
        /// </summary>
        /// <remarks>
        /// AI referral traffic for a project: human visits arriving from AI assistants (ChatGPT, Perplexity, Gemini, Claude, etc.), measured from the connected web analytics provider (Google Analytics 4, Adobe Analytics, PostHog, Plausible or Piano). Returns per-source users, sessions and conversions with totals and a conversion rate. Requires a connected provider and the Scale plan; otherwise returns ERR_AI_TRAFFIC_NOT_CONNECTED or ERR_PLAN_REQUIRED.
        /// </remarks>
        /// <param name="projectId">Project ID</param>
        /// <param name="range">Number of days to look back (alternative to from/to) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="source">Filter by a single AI source slug (e.g. chatgpt, perplexity, gemini, claude) (optional)</param>
        /// <param name="granularity"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetAiTrafficApiResponse"/>?&gt;</returns>
        Task<IGetAiTrafficApiResponse?> GetAiTrafficOrDefaultAsync(int projectId, Option<int> range = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<string> source = default, Option<string> granularity = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// AI bot catalog (Scale plan or above)
        /// </summary>
        /// <remarks>
        /// Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on the Scale plan or above.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="output">Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListAgentBotsApiResponse"/>&gt;</returns>
        Task<IListAgentBotsApiResponse> ListAgentBotsAsync(int projectId, Option<string> output = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// AI bot catalog (Scale plan or above)
        /// </summary>
        /// <remarks>
        /// Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on the Scale plan or above.
        /// </remarks>
        /// <param name="projectId">Project ID</param>
        /// <param name="output">Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListAgentBotsApiResponse"/>?&gt;</returns>
        Task<IListAgentBotsApiResponse?> ListAgentBotsOrDefaultAsync(int projectId, Option<string> output = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IGetAgentTrafficApiResponse"/>
    /// </summary>
    public interface IGetAgentTrafficApiResponse : LLMPulse.SDK.Client.IApiResponse, IOk<LLMPulse.SDK.Model.AgentTrafficResponse?>, IForbidden<LLMPulse.SDK.Model.ApiError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }
    }

    /// <summary>
    /// The <see cref="IGetAiTrafficApiResponse"/>
    /// </summary>
    public interface IGetAiTrafficApiResponse : LLMPulse.SDK.Client.IApiResponse, IForbidden<LLMPulse.SDK.Model.ApiError?>, INotFound<LLMPulse.SDK.Model.ApiError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// The <see cref="IListAgentBotsApiResponse"/>
    /// </summary>
    public interface IListAgentBotsApiResponse : LLMPulse.SDK.Client.IApiResponse, IOk<LLMPulse.SDK.Model.AgentBotsResponse?>, IForbidden<LLMPulse.SDK.Model.ApiError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class AIAgentTrafficApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetAgentTraffic;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetAgentTraffic;

        internal void ExecuteOnGetAgentTraffic(AIAgentTrafficApi.GetAgentTrafficApiResponse apiResponse)
        {
            OnGetAgentTraffic?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetAgentTraffic(Exception exception)
        {
            OnErrorGetAgentTraffic?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetAiTraffic;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetAiTraffic;

        internal void ExecuteOnGetAiTraffic(AIAgentTrafficApi.GetAiTrafficApiResponse apiResponse)
        {
            OnGetAiTraffic?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetAiTraffic(Exception exception)
        {
            OnErrorGetAiTraffic?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnListAgentBots;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorListAgentBots;

        internal void ExecuteOnListAgentBots(AIAgentTrafficApi.ListAgentBotsApiResponse apiResponse)
        {
            OnListAgentBots?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorListAgentBots(Exception exception)
        {
            OnErrorListAgentBots?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class AIAgentTrafficApi : IAIAgentTrafficApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<AIAgentTrafficApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public AIAgentTrafficApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AIAgentTrafficApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AIAgentTrafficApi(ILogger<AIAgentTrafficApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, AIAgentTrafficApiEvents aIAgentTrafficApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = aIAgentTrafficApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatGetAgentTraffic(ref int projectId, ref Option<int> range, ref Option<DateTime> from, ref Option<DateTime> to, ref Option<string> bot, ref Option<string> company, ref Option<string> groupBy, ref Option<string> granularity);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="bot"></param>
        /// <param name="company"></param>
        /// <param name="groupBy"></param>
        /// <param name="granularity"></param>
        /// <returns></returns>
        private void ValidateGetAgentTraffic(Option<string> bot, Option<string> company, Option<string> groupBy, Option<string> granularity)
        {
            if (bot.IsSet && bot.Value == null)
                throw new ArgumentNullException(nameof(bot));

            if (company.IsSet && company.Value == null)
                throw new ArgumentNullException(nameof(company));

            if (groupBy.IsSet && groupBy.Value == null)
                throw new ArgumentNullException(nameof(groupBy));

            if (granularity.IsSet && granularity.Value == null)
                throw new ArgumentNullException(nameof(granularity));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="range"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="bot"></param>
        /// <param name="company"></param>
        /// <param name="groupBy"></param>
        /// <param name="granularity"></param>
        private void AfterGetAgentTrafficDefaultImplementation(IGetAgentTrafficApiResponse apiResponseLocalVar, int projectId, Option<int> range, Option<DateTime> from, Option<DateTime> to, Option<string> bot, Option<string> company, Option<string> groupBy, Option<string> granularity)
        {
            bool suppressDefaultLog = false;
            AfterGetAgentTraffic(ref suppressDefaultLog, apiResponseLocalVar, projectId, range, from, to, bot, company, groupBy, granularity);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="range"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="bot"></param>
        /// <param name="company"></param>
        /// <param name="groupBy"></param>
        /// <param name="granularity"></param>
        partial void AfterGetAgentTraffic(ref bool suppressDefaultLog, IGetAgentTrafficApiResponse apiResponseLocalVar, int projectId, Option<int> range, Option<DateTime> from, Option<DateTime> to, Option<string> bot, Option<string> company, Option<string> groupBy, Option<string> granularity);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="range"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="bot"></param>
        /// <param name="company"></param>
        /// <param name="groupBy"></param>
        /// <param name="granularity"></param>
        private void OnErrorGetAgentTrafficDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<int> range, Option<DateTime> from, Option<DateTime> to, Option<string> bot, Option<string> company, Option<string> groupBy, Option<string> granularity)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetAgentTraffic(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, range, from, to, bot, company, groupBy, granularity);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="range"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="bot"></param>
        /// <param name="company"></param>
        /// <param name="groupBy"></param>
        /// <param name="granularity"></param>
        partial void OnErrorGetAgentTraffic(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<int> range, Option<DateTime> from, Option<DateTime> to, Option<string> bot, Option<string> company, Option<string> groupBy, Option<string> granularity);

        /// <summary>
        /// AI bot crawler traffic (Scale plan or above, Beta) Aggregated AI bot traffic hitting the project&#39;s origin server (GPTBot, PerplexityBot, ClaudeBot, OAI-SearchBot, Google-Extended, etc.). Sourced from Cloudflare or CSV uploads. Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED.
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="range">Number of days to look back (alternative to from/to) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="bot">Filter by bot slug (e.g. gptbot, claudebot, perplexitybot) (optional)</param>
        /// <param name="company">Filter by company (e.g. openai, anthropic, google) (optional)</param>
        /// <param name="groupBy"> (optional, default to bot)</param>
        /// <param name="granularity"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetAgentTrafficApiResponse"/>&gt;</returns>
        public async Task<IGetAgentTrafficApiResponse?> GetAgentTrafficOrDefaultAsync(int projectId, Option<int> range = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<string> bot = default, Option<string> company = default, Option<string> groupBy = default, Option<string> granularity = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetAgentTrafficAsync(projectId, range, from, to, bot, company, groupBy, granularity, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// AI bot crawler traffic (Scale plan or above, Beta) Aggregated AI bot traffic hitting the project&#39;s origin server (GPTBot, PerplexityBot, ClaudeBot, OAI-SearchBot, Google-Extended, etc.). Sourced from Cloudflare or CSV uploads. Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="range">Number of days to look back (alternative to from/to) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="bot">Filter by bot slug (e.g. gptbot, claudebot, perplexitybot) (optional)</param>
        /// <param name="company">Filter by company (e.g. openai, anthropic, google) (optional)</param>
        /// <param name="groupBy"> (optional, default to bot)</param>
        /// <param name="granularity"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetAgentTrafficApiResponse"/>&gt;</returns>
        public async Task<IGetAgentTrafficApiResponse> GetAgentTrafficAsync(int projectId, Option<int> range = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<string> bot = default, Option<string> company = default, Option<string> groupBy = default, Option<string> granularity = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetAgentTraffic(bot, company, groupBy, granularity);

                FormatGetAgentTraffic(ref projectId, ref range, ref from, ref to, ref bot, ref company, ref groupBy, ref granularity);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/metrics/agent_traffic"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/metrics/agent_traffic");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["project_id"] = ClientUtils.ParameterToString(projectId);

                    if (range.IsSet)
                        parseQueryStringLocalVar["range"] = ClientUtils.ParameterToString(range.Value);

                    if (from.IsSet)
                        parseQueryStringLocalVar["from"] = ClientUtils.ParameterToString(from.Value);

                    if (to.IsSet)
                        parseQueryStringLocalVar["to"] = ClientUtils.ParameterToString(to.Value);

                    if (bot.IsSet)
                        parseQueryStringLocalVar["bot"] = ClientUtils.ParameterToString(bot.Value);

                    if (company.IsSet)
                        parseQueryStringLocalVar["company"] = ClientUtils.ParameterToString(company.Value);

                    if (groupBy.IsSet)
                        parseQueryStringLocalVar["group_by"] = ClientUtils.ParameterToString(groupBy.Value);

                    if (granularity.IsSet)
                        parseQueryStringLocalVar["granularity"] = ClientUtils.ParameterToString(granularity.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        GetAgentTrafficApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/metrics/agent_traffic", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetAgentTrafficDefaultImplementation(apiResponseLocalVar, projectId, range, from, to, bot, company, groupBy, granularity);

                        Events.ExecuteOnGetAgentTraffic(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetAgentTrafficDefaultImplementation(e, "/metrics/agent_traffic", uriBuilderLocalVar.Path, projectId, range, from, to, bot, company, groupBy, granularity);
                Events.ExecuteOnErrorGetAgentTraffic(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetAgentTrafficApiResponse"/>
        /// </summary>
        public partial class GetAgentTrafficApiResponse : LLMPulse.SDK.Client.ApiResponse, IGetAgentTrafficApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<AIAgentTrafficApi> Logger { get; }

            /// <summary>
            /// The <see cref="GetAgentTrafficApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetAgentTrafficApiResponse(ILogger<AIAgentTrafficApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetAgentTrafficApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetAgentTrafficApiResponse(ILogger<AIAgentTrafficApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.AgentTrafficResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.AgentTrafficResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out LLMPulse.SDK.Model.AgentTrafficResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? Forbidden()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetAiTraffic(ref int projectId, ref Option<int> range, ref Option<DateTime> from, ref Option<DateTime> to, ref Option<string> source, ref Option<string> granularity);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="source"></param>
        /// <param name="granularity"></param>
        /// <returns></returns>
        private void ValidateGetAiTraffic(Option<string> source, Option<string> granularity)
        {
            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source));

            if (granularity.IsSet && granularity.Value == null)
                throw new ArgumentNullException(nameof(granularity));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="range"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="source"></param>
        /// <param name="granularity"></param>
        private void AfterGetAiTrafficDefaultImplementation(IGetAiTrafficApiResponse apiResponseLocalVar, int projectId, Option<int> range, Option<DateTime> from, Option<DateTime> to, Option<string> source, Option<string> granularity)
        {
            bool suppressDefaultLog = false;
            AfterGetAiTraffic(ref suppressDefaultLog, apiResponseLocalVar, projectId, range, from, to, source, granularity);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="range"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="source"></param>
        /// <param name="granularity"></param>
        partial void AfterGetAiTraffic(ref bool suppressDefaultLog, IGetAiTrafficApiResponse apiResponseLocalVar, int projectId, Option<int> range, Option<DateTime> from, Option<DateTime> to, Option<string> source, Option<string> granularity);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="range"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="source"></param>
        /// <param name="granularity"></param>
        private void OnErrorGetAiTrafficDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<int> range, Option<DateTime> from, Option<DateTime> to, Option<string> source, Option<string> granularity)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetAiTraffic(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, range, from, to, source, granularity);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="range"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="source"></param>
        /// <param name="granularity"></param>
        partial void OnErrorGetAiTraffic(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<int> range, Option<DateTime> from, Option<DateTime> to, Option<string> source, Option<string> granularity);

        /// <summary>
        /// AI referral traffic (Scale plan or above) AI referral traffic for a project: human visits arriving from AI assistants (ChatGPT, Perplexity, Gemini, Claude, etc.), measured from the connected web analytics provider (Google Analytics 4, Adobe Analytics, PostHog, Plausible or Piano). Returns per-source users, sessions and conversions with totals and a conversion rate. Requires a connected provider and the Scale plan; otherwise returns ERR_AI_TRAFFIC_NOT_CONNECTED or ERR_PLAN_REQUIRED.
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="range">Number of days to look back (alternative to from/to) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="source">Filter by a single AI source slug (e.g. chatgpt, perplexity, gemini, claude) (optional)</param>
        /// <param name="granularity"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetAiTrafficApiResponse"/>&gt;</returns>
        public async Task<IGetAiTrafficApiResponse?> GetAiTrafficOrDefaultAsync(int projectId, Option<int> range = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<string> source = default, Option<string> granularity = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetAiTrafficAsync(projectId, range, from, to, source, granularity, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// AI referral traffic (Scale plan or above) AI referral traffic for a project: human visits arriving from AI assistants (ChatGPT, Perplexity, Gemini, Claude, etc.), measured from the connected web analytics provider (Google Analytics 4, Adobe Analytics, PostHog, Plausible or Piano). Returns per-source users, sessions and conversions with totals and a conversion rate. Requires a connected provider and the Scale plan; otherwise returns ERR_AI_TRAFFIC_NOT_CONNECTED or ERR_PLAN_REQUIRED.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="range">Number of days to look back (alternative to from/to) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="source">Filter by a single AI source slug (e.g. chatgpt, perplexity, gemini, claude) (optional)</param>
        /// <param name="granularity"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetAiTrafficApiResponse"/>&gt;</returns>
        public async Task<IGetAiTrafficApiResponse> GetAiTrafficAsync(int projectId, Option<int> range = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<string> source = default, Option<string> granularity = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetAiTraffic(source, granularity);

                FormatGetAiTraffic(ref projectId, ref range, ref from, ref to, ref source, ref granularity);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/metrics/ai_traffic"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/metrics/ai_traffic");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["project_id"] = ClientUtils.ParameterToString(projectId);

                    if (range.IsSet)
                        parseQueryStringLocalVar["range"] = ClientUtils.ParameterToString(range.Value);

                    if (from.IsSet)
                        parseQueryStringLocalVar["from"] = ClientUtils.ParameterToString(from.Value);

                    if (to.IsSet)
                        parseQueryStringLocalVar["to"] = ClientUtils.ParameterToString(to.Value);

                    if (source.IsSet)
                        parseQueryStringLocalVar["source"] = ClientUtils.ParameterToString(source.Value);

                    if (granularity.IsSet)
                        parseQueryStringLocalVar["granularity"] = ClientUtils.ParameterToString(granularity.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        GetAiTrafficApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/metrics/ai_traffic", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetAiTrafficDefaultImplementation(apiResponseLocalVar, projectId, range, from, to, source, granularity);

                        Events.ExecuteOnGetAiTraffic(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetAiTrafficDefaultImplementation(e, "/metrics/ai_traffic", uriBuilderLocalVar.Path, projectId, range, from, to, source, granularity);
                Events.ExecuteOnErrorGetAiTraffic(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetAiTrafficApiResponse"/>
        /// </summary>
        public partial class GetAiTrafficApiResponse : LLMPulse.SDK.Client.ApiResponse, IGetAiTrafficApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<AIAgentTrafficApi> Logger { get; }

            /// <summary>
            /// The <see cref="GetAiTrafficApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetAiTrafficApiResponse(ILogger<AIAgentTrafficApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetAiTrafficApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetAiTrafficApiResponse(ILogger<AIAgentTrafficApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? Forbidden()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatListAgentBots(ref int projectId, ref Option<string> output);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="output"></param>
        /// <returns></returns>
        private void ValidateListAgentBots(Option<string> output)
        {
            if (output.IsSet && output.Value == null)
                throw new ArgumentNullException(nameof(output));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="output"></param>
        private void AfterListAgentBotsDefaultImplementation(IListAgentBotsApiResponse apiResponseLocalVar, int projectId, Option<string> output)
        {
            bool suppressDefaultLog = false;
            AfterListAgentBots(ref suppressDefaultLog, apiResponseLocalVar, projectId, output);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="output"></param>
        partial void AfterListAgentBots(ref bool suppressDefaultLog, IListAgentBotsApiResponse apiResponseLocalVar, int projectId, Option<string> output);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="output"></param>
        private void OnErrorListAgentBotsDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<string> output)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorListAgentBots(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, output);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="output"></param>
        partial void OnErrorListAgentBots(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<string> output);

        /// <summary>
        /// AI bot catalog (Scale plan or above) Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on the Scale plan or above.
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="output">Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListAgentBotsApiResponse"/>&gt;</returns>
        public async Task<IListAgentBotsApiResponse?> ListAgentBotsOrDefaultAsync(int projectId, Option<string> output = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ListAgentBotsAsync(projectId, output, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// AI bot catalog (Scale plan or above) Static catalog of AI bots that Agent Analytics can identify. Useful for rendering filter UIs that mirror our internal classification (slug, display name, company, category, Cloudflare verified-bot mapping, description). Requires the Scale plan; lower tiers receive ERR_PLAN_REQUIRED. The equivalent MCP tool list_agent_bots is available on the Scale plan or above.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="output">Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListAgentBotsApiResponse"/>&gt;</returns>
        public async Task<IListAgentBotsApiResponse> ListAgentBotsAsync(int projectId, Option<string> output = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateListAgentBots(output);

                FormatListAgentBots(ref projectId, ref output);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/dimensions/agent_bots"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/dimensions/agent_bots");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["project_id"] = ClientUtils.ParameterToString(projectId);

                    if (output.IsSet)
                        parseQueryStringLocalVar["output"] = ClientUtils.ParameterToString(output.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ListAgentBotsApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/dimensions/agent_bots", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterListAgentBotsDefaultImplementation(apiResponseLocalVar, projectId, output);

                        Events.ExecuteOnListAgentBots(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorListAgentBotsDefaultImplementation(e, "/dimensions/agent_bots", uriBuilderLocalVar.Path, projectId, output);
                Events.ExecuteOnErrorListAgentBots(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ListAgentBotsApiResponse"/>
        /// </summary>
        public partial class ListAgentBotsApiResponse : LLMPulse.SDK.Client.ApiResponse, IListAgentBotsApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<AIAgentTrafficApi> Logger { get; }

            /// <summary>
            /// The <see cref="ListAgentBotsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListAgentBotsApiResponse(ILogger<AIAgentTrafficApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ListAgentBotsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListAgentBotsApiResponse(ILogger<AIAgentTrafficApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.AgentBotsResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.AgentBotsResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out LLMPulse.SDK.Model.AgentBotsResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? Forbidden()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
