// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using LLMPulse.SDK.Client;
using LLMPulse.SDK.Logging;
using LLMPulse.SDK.Model;
using System.Diagnostics.CodeAnalysis;

namespace LLMPulse.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ISentimentsApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        SentimentsApiEvents Events { get; }

        /// <summary>
        /// List sentiment categories
        /// </summary>
        /// <remarks>
        /// Sentiment metric keys + labels + colors. For records, use /sentiments.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="output">Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListSentimentCategoriesApiResponse"/>&gt;</returns>
        Task<IListSentimentCategoriesApiResponse> ListSentimentCategoriesAsync(int projectId, Option<string> output = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List sentiment categories
        /// </summary>
        /// <remarks>
        /// Sentiment metric keys + labels + colors. For records, use /sentiments.
        /// </remarks>
        /// <param name="projectId">Project ID</param>
        /// <param name="output">Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListSentimentCategoriesApiResponse"/>?&gt;</returns>
        Task<IListSentimentCategoriesApiResponse?> ListSentimentCategoriesOrDefaultAsync(int projectId, Option<string> output = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List sentiment records
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="competitorId"> (optional)</param>
        /// <param name="brandOnly"> (optional)</param>
        /// <param name="analysis">One sentiment level or a comma-separated list: very_positive, positive, neutral, negative, very_negative (optional)</param>
        /// <param name="model">Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)</param>
        /// <param name="collectionId">One collection/tag ID or a comma-separated list of IDs (optional)</param>
        /// <param name="countryCode">One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)</param>
        /// <param name="languageCode">One ISO language code or a comma-separated list (e.g. en,es,de) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="perPage"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListSentimentRecordsApiResponse"/>&gt;</returns>
        Task<IListSentimentRecordsApiResponse> ListSentimentRecordsAsync(int projectId, Option<int> competitorId = default, Option<bool> brandOnly = default, Option<string> analysis = default, Option<string> model = default, Option<GetTimeseriesCollectionIdParameter> collectionId = default, Option<string> countryCode = default, Option<string> languageCode = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List sentiment records
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="projectId">Project ID</param>
        /// <param name="competitorId"> (optional)</param>
        /// <param name="brandOnly"> (optional)</param>
        /// <param name="analysis">One sentiment level or a comma-separated list: very_positive, positive, neutral, negative, very_negative (optional)</param>
        /// <param name="model">Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)</param>
        /// <param name="collectionId">One collection/tag ID or a comma-separated list of IDs (optional)</param>
        /// <param name="countryCode">One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)</param>
        /// <param name="languageCode">One ISO language code or a comma-separated list (e.g. en,es,de) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="perPage"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListSentimentRecordsApiResponse"/>?&gt;</returns>
        Task<IListSentimentRecordsApiResponse?> ListSentimentRecordsOrDefaultAsync(int projectId, Option<int> competitorId = default, Option<bool> brandOnly = default, Option<string> analysis = default, Option<string> model = default, Option<GetTimeseriesCollectionIdParameter> collectionId = default, Option<string> countryCode = default, Option<string> languageCode = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IListSentimentCategoriesApiResponse"/>
    /// </summary>
    public interface IListSentimentCategoriesApiResponse : LLMPulse.SDK.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IListSentimentRecordsApiResponse"/>
    /// </summary>
    public interface IListSentimentRecordsApiResponse : LLMPulse.SDK.Client.IApiResponse, IUnprocessableContent<LLMPulse.SDK.Model.ApiError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class SentimentsApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnListSentimentCategories;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorListSentimentCategories;

        internal void ExecuteOnListSentimentCategories(SentimentsApi.ListSentimentCategoriesApiResponse apiResponse)
        {
            OnListSentimentCategories?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorListSentimentCategories(Exception exception)
        {
            OnErrorListSentimentCategories?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnListSentimentRecords;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorListSentimentRecords;

        internal void ExecuteOnListSentimentRecords(SentimentsApi.ListSentimentRecordsApiResponse apiResponse)
        {
            OnListSentimentRecords?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorListSentimentRecords(Exception exception)
        {
            OnErrorListSentimentRecords?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class SentimentsApi : ISentimentsApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<SentimentsApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public SentimentsApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="SentimentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SentimentsApi(ILogger<SentimentsApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, SentimentsApiEvents sentimentsApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = sentimentsApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatListSentimentCategories(ref int projectId, ref Option<string> output);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="output"></param>
        /// <returns></returns>
        private void ValidateListSentimentCategories(Option<string> output)
        {
            if (output.IsSet && output.Value == null)
                throw new ArgumentNullException(nameof(output));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="output"></param>
        private void AfterListSentimentCategoriesDefaultImplementation(IListSentimentCategoriesApiResponse apiResponseLocalVar, int projectId, Option<string> output)
        {
            bool suppressDefaultLog = false;
            AfterListSentimentCategories(ref suppressDefaultLog, apiResponseLocalVar, projectId, output);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="output"></param>
        partial void AfterListSentimentCategories(ref bool suppressDefaultLog, IListSentimentCategoriesApiResponse apiResponseLocalVar, int projectId, Option<string> output);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="output"></param>
        private void OnErrorListSentimentCategoriesDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<string> output)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorListSentimentCategories(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, output);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="output"></param>
        partial void OnErrorListSentimentCategories(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<string> output);

        /// <summary>
        /// List sentiment categories Sentiment metric keys + labels + colors. For records, use /sentiments.
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="output">Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListSentimentCategoriesApiResponse"/>&gt;</returns>
        public async Task<IListSentimentCategoriesApiResponse?> ListSentimentCategoriesOrDefaultAsync(int projectId, Option<string> output = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ListSentimentCategoriesAsync(projectId, output, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// List sentiment categories Sentiment metric keys + labels + colors. For records, use /sentiments.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="output">Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListSentimentCategoriesApiResponse"/>&gt;</returns>
        public async Task<IListSentimentCategoriesApiResponse> ListSentimentCategoriesAsync(int projectId, Option<string> output = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateListSentimentCategories(output);

                FormatListSentimentCategories(ref projectId, ref output);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/dimensions/sentiments"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/dimensions/sentiments");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["project_id"] = ClientUtils.ParameterToString(projectId);

                    if (output.IsSet)
                        parseQueryStringLocalVar["output"] = ClientUtils.ParameterToString(output.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ListSentimentCategoriesApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/dimensions/sentiments", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterListSentimentCategoriesDefaultImplementation(apiResponseLocalVar, projectId, output);

                        Events.ExecuteOnListSentimentCategories(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorListSentimentCategoriesDefaultImplementation(e, "/dimensions/sentiments", uriBuilderLocalVar.Path, projectId, output);
                Events.ExecuteOnErrorListSentimentCategories(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ListSentimentCategoriesApiResponse"/>
        /// </summary>
        public partial class ListSentimentCategoriesApiResponse : LLMPulse.SDK.Client.ApiResponse, IListSentimentCategoriesApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<SentimentsApi> Logger { get; }

            /// <summary>
            /// The <see cref="ListSentimentCategoriesApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListSentimentCategoriesApiResponse(ILogger<SentimentsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ListSentimentCategoriesApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListSentimentCategoriesApiResponse(ILogger<SentimentsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatListSentimentRecords(ref int projectId, ref Option<int> competitorId, ref Option<bool> brandOnly, ref Option<string> analysis, ref Option<string> model, Option<GetTimeseriesCollectionIdParameter> collectionId, ref Option<string> countryCode, ref Option<string> languageCode, ref Option<DateTime> from, ref Option<DateTime> to, ref Option<int> page, ref Option<int> perPage);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="analysis"></param>
        /// <param name="model"></param>
        /// <param name="collectionId"></param>
        /// <param name="countryCode"></param>
        /// <param name="languageCode"></param>
        /// <returns></returns>
        private void ValidateListSentimentRecords(Option<string> analysis, Option<string> model, Option<GetTimeseriesCollectionIdParameter> collectionId, Option<string> countryCode, Option<string> languageCode)
        {
            if (analysis.IsSet && analysis.Value == null)
                throw new ArgumentNullException(nameof(analysis));

            if (model.IsSet && model.Value == null)
                throw new ArgumentNullException(nameof(model));

            if (collectionId.IsSet && collectionId.Value == null)
                throw new ArgumentNullException(nameof(collectionId));

            if (countryCode.IsSet && countryCode.Value == null)
                throw new ArgumentNullException(nameof(countryCode));

            if (languageCode.IsSet && languageCode.Value == null)
                throw new ArgumentNullException(nameof(languageCode));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="competitorId"></param>
        /// <param name="brandOnly"></param>
        /// <param name="analysis"></param>
        /// <param name="model"></param>
        /// <param name="collectionId"></param>
        /// <param name="countryCode"></param>
        /// <param name="languageCode"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        private void AfterListSentimentRecordsDefaultImplementation(IListSentimentRecordsApiResponse apiResponseLocalVar, int projectId, Option<int> competitorId, Option<bool> brandOnly, Option<string> analysis, Option<string> model, Option<GetTimeseriesCollectionIdParameter> collectionId, Option<string> countryCode, Option<string> languageCode, Option<DateTime> from, Option<DateTime> to, Option<int> page, Option<int> perPage)
        {
            bool suppressDefaultLog = false;
            AfterListSentimentRecords(ref suppressDefaultLog, apiResponseLocalVar, projectId, competitorId, brandOnly, analysis, model, collectionId, countryCode, languageCode, from, to, page, perPage);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="competitorId"></param>
        /// <param name="brandOnly"></param>
        /// <param name="analysis"></param>
        /// <param name="model"></param>
        /// <param name="collectionId"></param>
        /// <param name="countryCode"></param>
        /// <param name="languageCode"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        partial void AfterListSentimentRecords(ref bool suppressDefaultLog, IListSentimentRecordsApiResponse apiResponseLocalVar, int projectId, Option<int> competitorId, Option<bool> brandOnly, Option<string> analysis, Option<string> model, Option<GetTimeseriesCollectionIdParameter> collectionId, Option<string> countryCode, Option<string> languageCode, Option<DateTime> from, Option<DateTime> to, Option<int> page, Option<int> perPage);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="competitorId"></param>
        /// <param name="brandOnly"></param>
        /// <param name="analysis"></param>
        /// <param name="model"></param>
        /// <param name="collectionId"></param>
        /// <param name="countryCode"></param>
        /// <param name="languageCode"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        private void OnErrorListSentimentRecordsDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<int> competitorId, Option<bool> brandOnly, Option<string> analysis, Option<string> model, Option<GetTimeseriesCollectionIdParameter> collectionId, Option<string> countryCode, Option<string> languageCode, Option<DateTime> from, Option<DateTime> to, Option<int> page, Option<int> perPage)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorListSentimentRecords(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, competitorId, brandOnly, analysis, model, collectionId, countryCode, languageCode, from, to, page, perPage);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="competitorId"></param>
        /// <param name="brandOnly"></param>
        /// <param name="analysis"></param>
        /// <param name="model"></param>
        /// <param name="collectionId"></param>
        /// <param name="countryCode"></param>
        /// <param name="languageCode"></param>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        partial void OnErrorListSentimentRecords(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, Option<int> competitorId, Option<bool> brandOnly, Option<string> analysis, Option<string> model, Option<GetTimeseriesCollectionIdParameter> collectionId, Option<string> countryCode, Option<string> languageCode, Option<DateTime> from, Option<DateTime> to, Option<int> page, Option<int> perPage);

        /// <summary>
        /// List sentiment records 
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="competitorId"> (optional)</param>
        /// <param name="brandOnly"> (optional)</param>
        /// <param name="analysis">One sentiment level or a comma-separated list: very_positive, positive, neutral, negative, very_negative (optional)</param>
        /// <param name="model">Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)</param>
        /// <param name="collectionId">One collection/tag ID or a comma-separated list of IDs (optional)</param>
        /// <param name="countryCode">One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)</param>
        /// <param name="languageCode">One ISO language code or a comma-separated list (e.g. en,es,de) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="perPage"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListSentimentRecordsApiResponse"/>&gt;</returns>
        public async Task<IListSentimentRecordsApiResponse?> ListSentimentRecordsOrDefaultAsync(int projectId, Option<int> competitorId = default, Option<bool> brandOnly = default, Option<string> analysis = default, Option<string> model = default, Option<GetTimeseriesCollectionIdParameter> collectionId = default, Option<string> countryCode = default, Option<string> languageCode = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ListSentimentRecordsAsync(projectId, competitorId, brandOnly, analysis, model, collectionId, countryCode, languageCode, from, to, page, perPage, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// List sentiment records 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="competitorId"> (optional)</param>
        /// <param name="brandOnly"> (optional)</param>
        /// <param name="analysis">One sentiment level or a comma-separated list: very_positive, positive, neutral, negative, very_negative (optional)</param>
        /// <param name="model">Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)</param>
        /// <param name="collectionId">One collection/tag ID or a comma-separated list of IDs (optional)</param>
        /// <param name="countryCode">One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)</param>
        /// <param name="languageCode">One ISO language code or a comma-separated list (e.g. en,es,de) (optional)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to">End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="perPage"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListSentimentRecordsApiResponse"/>&gt;</returns>
        public async Task<IListSentimentRecordsApiResponse> ListSentimentRecordsAsync(int projectId, Option<int> competitorId = default, Option<bool> brandOnly = default, Option<string> analysis = default, Option<string> model = default, Option<GetTimeseriesCollectionIdParameter> collectionId = default, Option<string> countryCode = default, Option<string> languageCode = default, Option<DateTime> from = default, Option<DateTime> to = default, Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateListSentimentRecords(analysis, model, collectionId, countryCode, languageCode);

                FormatListSentimentRecords(ref projectId, ref competitorId, ref brandOnly, ref analysis, ref model, collectionId, ref countryCode, ref languageCode, ref from, ref to, ref page, ref perPage);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/sentiments"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/sentiments");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["project_id"] = ClientUtils.ParameterToString(projectId);

                    if (competitorId.IsSet)
                        parseQueryStringLocalVar["competitor_id"] = ClientUtils.ParameterToString(competitorId.Value);

                    if (brandOnly.IsSet)
                        parseQueryStringLocalVar["brand_only"] = ClientUtils.ParameterToString(brandOnly.Value);

                    if (analysis.IsSet)
                        parseQueryStringLocalVar["analysis"] = ClientUtils.ParameterToString(analysis.Value);

                    if (model.IsSet)
                        parseQueryStringLocalVar["model"] = ClientUtils.ParameterToString(model.Value);

                    if (collectionId.IsSet)
                        parseQueryStringLocalVar["collection_id"] = ClientUtils.ParameterToString(collectionId.Value);

                    if (countryCode.IsSet)
                        parseQueryStringLocalVar["country_code"] = ClientUtils.ParameterToString(countryCode.Value);

                    if (languageCode.IsSet)
                        parseQueryStringLocalVar["language_code"] = ClientUtils.ParameterToString(languageCode.Value);

                    if (from.IsSet)
                        parseQueryStringLocalVar["from"] = ClientUtils.ParameterToString(from.Value);

                    if (to.IsSet)
                        parseQueryStringLocalVar["to"] = ClientUtils.ParameterToString(to.Value);

                    if (page.IsSet)
                        parseQueryStringLocalVar["page"] = ClientUtils.ParameterToString(page.Value);

                    if (perPage.IsSet)
                        parseQueryStringLocalVar["per_page"] = ClientUtils.ParameterToString(perPage.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ListSentimentRecordsApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/sentiments", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterListSentimentRecordsDefaultImplementation(apiResponseLocalVar, projectId, competitorId, brandOnly, analysis, model, collectionId, countryCode, languageCode, from, to, page, perPage);

                        Events.ExecuteOnListSentimentRecords(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorListSentimentRecordsDefaultImplementation(e, "/sentiments", uriBuilderLocalVar.Path, projectId, competitorId, brandOnly, analysis, model, collectionId, countryCode, languageCode, from, to, page, perPage);
                Events.ExecuteOnErrorListSentimentRecords(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ListSentimentRecordsApiResponse"/>
        /// </summary>
        public partial class ListSentimentRecordsApiResponse : LLMPulse.SDK.Client.ApiResponse, IListSentimentRecordsApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<SentimentsApi> Logger { get; }

            /// <summary>
            /// The <see cref="ListSentimentRecordsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListSentimentRecordsApiResponse(ILogger<SentimentsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ListSentimentRecordsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListSentimentRecordsApiResponse(ILogger<SentimentsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
