// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using LLMPulse.SDK.Client;
using LLMPulse.SDK.Logging;
using LLMPulse.SDK.Model;
using System.Diagnostics.CodeAnalysis;

namespace LLMPulse.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ITechnicalGEOReportsApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        TechnicalGEOReportsApiEvents Events { get; }

        /// <summary>
        /// Run technical GEO analysis
        /// </summary>
        /// <remarks>
        /// Launches the full technical GEO analysis bundle (crawlability, schema, content readiness, discoverability, site structure, robots.txt, agent readiness, llms.txt, AI visibility) for a URL + country. Each report runs in a background job. Requires a &#x60;read_write&#x60; scope API key.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateTechnicalGeoReportsApiResponse"/>&gt;</returns>
        Task<ICreateTechnicalGeoReportsApiResponse> CreateTechnicalGeoReportsAsync(CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Run technical GEO analysis
        /// </summary>
        /// <remarks>
        /// Launches the full technical GEO analysis bundle (crawlability, schema, content readiness, discoverability, site structure, robots.txt, agent readiness, llms.txt, AI visibility) for a URL + country. Each report runs in a background job. Requires a &#x60;read_write&#x60; scope API key.
        /// </remarks>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateTechnicalGeoReportsApiResponse"/>?&gt;</returns>
        Task<ICreateTechnicalGeoReportsApiResponse?> CreateTechnicalGeoReportsOrDefaultAsync(CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get a technical GEO report
        /// </summary>
        /// <remarks>
        /// Returns the current status and the full result_data once the report is completed. While it is running, result_data is null and poll_after_seconds tells clients when to check again.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="reportType"></param>
        /// <param name="id">Report id returned by POST /technical_geo_reports or GET /technical_geo_reports</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetTechnicalGeoReportApiResponse"/>&gt;</returns>
        Task<IGetTechnicalGeoReportApiResponse> GetTechnicalGeoReportAsync(int projectId, string reportType, int id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get a technical GEO report
        /// </summary>
        /// <remarks>
        /// Returns the current status and the full result_data once the report is completed. While it is running, result_data is null and poll_after_seconds tells clients when to check again.
        /// </remarks>
        /// <param name="projectId">Project ID</param>
        /// <param name="reportType"></param>
        /// <param name="id">Report id returned by POST /technical_geo_reports or GET /technical_geo_reports</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetTechnicalGeoReportApiResponse"/>?&gt;</returns>
        Task<IGetTechnicalGeoReportApiResponse?> GetTechnicalGeoReportOrDefaultAsync(int projectId, string reportType, int id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List technical GEO reports
        /// </summary>
        /// <remarks>
        /// Lists reports of one technical GEO type for a project, newest first. Use agent_readiness for the AI/Agent Readiness report.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="reportType"></param>
        /// <param name="status">Optional status filter; valid values depend on report_type (optional)</param>
        /// <param name="batchId">Optional batch id returned when the report bundle was created (optional)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="perPage"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListTechnicalGeoReportsApiResponse"/>&gt;</returns>
        Task<IListTechnicalGeoReportsApiResponse> ListTechnicalGeoReportsAsync(int projectId, string reportType, Option<string> status = default, Option<int> batchId = default, Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List technical GEO reports
        /// </summary>
        /// <remarks>
        /// Lists reports of one technical GEO type for a project, newest first. Use agent_readiness for the AI/Agent Readiness report.
        /// </remarks>
        /// <param name="projectId">Project ID</param>
        /// <param name="reportType"></param>
        /// <param name="status">Optional status filter; valid values depend on report_type (optional)</param>
        /// <param name="batchId">Optional batch id returned when the report bundle was created (optional)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="perPage"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListTechnicalGeoReportsApiResponse"/>?&gt;</returns>
        Task<IListTechnicalGeoReportsApiResponse?> ListTechnicalGeoReportsOrDefaultAsync(int projectId, string reportType, Option<string> status = default, Option<int> batchId = default, Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ICreateTechnicalGeoReportsApiResponse"/>
    /// </summary>
    public interface ICreateTechnicalGeoReportsApiResponse : LLMPulse.SDK.Client.IApiResponse, IForbidden<LLMPulse.SDK.Model.ApiError?>, IUnprocessableContent<LLMPulse.SDK.Model.ApiError?>
    {
        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }
    }

    /// <summary>
    /// The <see cref="IGetTechnicalGeoReportApiResponse"/>
    /// </summary>
    public interface IGetTechnicalGeoReportApiResponse : LLMPulse.SDK.Client.IApiResponse, INotFound<LLMPulse.SDK.Model.ApiError?>, IUnprocessableContent<LLMPulse.SDK.Model.ApiError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }
    }

    /// <summary>
    /// The <see cref="IListTechnicalGeoReportsApiResponse"/>
    /// </summary>
    public interface IListTechnicalGeoReportsApiResponse : LLMPulse.SDK.Client.IApiResponse, IUnprocessableContent<LLMPulse.SDK.Model.ApiError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class TechnicalGEOReportsApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnCreateTechnicalGeoReports;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorCreateTechnicalGeoReports;

        internal void ExecuteOnCreateTechnicalGeoReports(TechnicalGEOReportsApi.CreateTechnicalGeoReportsApiResponse apiResponse)
        {
            OnCreateTechnicalGeoReports?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorCreateTechnicalGeoReports(Exception exception)
        {
            OnErrorCreateTechnicalGeoReports?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetTechnicalGeoReport;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetTechnicalGeoReport;

        internal void ExecuteOnGetTechnicalGeoReport(TechnicalGEOReportsApi.GetTechnicalGeoReportApiResponse apiResponse)
        {
            OnGetTechnicalGeoReport?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetTechnicalGeoReport(Exception exception)
        {
            OnErrorGetTechnicalGeoReport?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnListTechnicalGeoReports;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorListTechnicalGeoReports;

        internal void ExecuteOnListTechnicalGeoReports(TechnicalGEOReportsApi.ListTechnicalGeoReportsApiResponse apiResponse)
        {
            OnListTechnicalGeoReports?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorListTechnicalGeoReports(Exception exception)
        {
            OnErrorListTechnicalGeoReports?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class TechnicalGEOReportsApi : ITechnicalGEOReportsApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<TechnicalGEOReportsApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public TechnicalGEOReportsApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TechnicalGEOReportsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TechnicalGEOReportsApi(ILogger<TechnicalGEOReportsApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, TechnicalGEOReportsApiEvents technicalGEOReportsApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = technicalGEOReportsApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatCreateTechnicalGeoReports(CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        /// <returns></returns>
        private void ValidateCreateTechnicalGeoReports(CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest)
        {
            if (createTechnicalGeoReportsRequest == null)
                throw new ArgumentNullException(nameof(createTechnicalGeoReportsRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        private void AfterCreateTechnicalGeoReportsDefaultImplementation(ICreateTechnicalGeoReportsApiResponse apiResponseLocalVar, CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest)
        {
            bool suppressDefaultLog = false;
            AfterCreateTechnicalGeoReports(ref suppressDefaultLog, apiResponseLocalVar, createTechnicalGeoReportsRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        partial void AfterCreateTechnicalGeoReports(ref bool suppressDefaultLog, ICreateTechnicalGeoReportsApiResponse apiResponseLocalVar, CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        private void OnErrorCreateTechnicalGeoReportsDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorCreateTechnicalGeoReports(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, createTechnicalGeoReportsRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        partial void OnErrorCreateTechnicalGeoReports(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest);

        /// <summary>
        /// Run technical GEO analysis Launches the full technical GEO analysis bundle (crawlability, schema, content readiness, discoverability, site structure, robots.txt, agent readiness, llms.txt, AI visibility) for a URL + country. Each report runs in a background job. Requires a &#x60;read_write&#x60; scope API key.
        /// </summary>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateTechnicalGeoReportsApiResponse"/>&gt;</returns>
        public async Task<ICreateTechnicalGeoReportsApiResponse?> CreateTechnicalGeoReportsOrDefaultAsync(CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await CreateTechnicalGeoReportsAsync(createTechnicalGeoReportsRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Run technical GEO analysis Launches the full technical GEO analysis bundle (crawlability, schema, content readiness, discoverability, site structure, robots.txt, agent readiness, llms.txt, AI visibility) for a URL + country. Each report runs in a background job. Requires a &#x60;read_write&#x60; scope API key.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="createTechnicalGeoReportsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateTechnicalGeoReportsApiResponse"/>&gt;</returns>
        public async Task<ICreateTechnicalGeoReportsApiResponse> CreateTechnicalGeoReportsAsync(CreateTechnicalGeoReportsRequest createTechnicalGeoReportsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateCreateTechnicalGeoReports(createTechnicalGeoReportsRequest);

                FormatCreateTechnicalGeoReports(createTechnicalGeoReportsRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/technical_geo_reports"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/technical_geo_reports");

                    httpRequestMessageLocalVar.Content = (createTechnicalGeoReportsRequest as object) is LLMPulse.SDK.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(createTechnicalGeoReportsRequest, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        CreateTechnicalGeoReportsApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/technical_geo_reports", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterCreateTechnicalGeoReportsDefaultImplementation(apiResponseLocalVar, createTechnicalGeoReportsRequest);

                        Events.ExecuteOnCreateTechnicalGeoReports(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorCreateTechnicalGeoReportsDefaultImplementation(e, "/technical_geo_reports", uriBuilderLocalVar.Path, createTechnicalGeoReportsRequest);
                Events.ExecuteOnErrorCreateTechnicalGeoReports(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="CreateTechnicalGeoReportsApiResponse"/>
        /// </summary>
        public partial class CreateTechnicalGeoReportsApiResponse : LLMPulse.SDK.Client.ApiResponse, ICreateTechnicalGeoReportsApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TechnicalGEOReportsApi> Logger { get; }

            /// <summary>
            /// The <see cref="CreateTechnicalGeoReportsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateTechnicalGeoReportsApiResponse(ILogger<TechnicalGEOReportsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="CreateTechnicalGeoReportsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateTechnicalGeoReportsApiResponse(ILogger<TechnicalGEOReportsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => 201 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? Forbidden()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetTechnicalGeoReport(ref int projectId, ref string reportType, ref int id);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="reportType"></param>
        /// <returns></returns>
        private void ValidateGetTechnicalGeoReport(string reportType)
        {
            if (reportType == null)
                throw new ArgumentNullException(nameof(reportType));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="reportType"></param>
        /// <param name="id"></param>
        private void AfterGetTechnicalGeoReportDefaultImplementation(IGetTechnicalGeoReportApiResponse apiResponseLocalVar, int projectId, string reportType, int id)
        {
            bool suppressDefaultLog = false;
            AfterGetTechnicalGeoReport(ref suppressDefaultLog, apiResponseLocalVar, projectId, reportType, id);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="reportType"></param>
        /// <param name="id"></param>
        partial void AfterGetTechnicalGeoReport(ref bool suppressDefaultLog, IGetTechnicalGeoReportApiResponse apiResponseLocalVar, int projectId, string reportType, int id);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="reportType"></param>
        /// <param name="id"></param>
        private void OnErrorGetTechnicalGeoReportDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, string reportType, int id)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetTechnicalGeoReport(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, reportType, id);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="reportType"></param>
        /// <param name="id"></param>
        partial void OnErrorGetTechnicalGeoReport(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, string reportType, int id);

        /// <summary>
        /// Get a technical GEO report Returns the current status and the full result_data once the report is completed. While it is running, result_data is null and poll_after_seconds tells clients when to check again.
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="reportType"></param>
        /// <param name="id">Report id returned by POST /technical_geo_reports or GET /technical_geo_reports</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetTechnicalGeoReportApiResponse"/>&gt;</returns>
        public async Task<IGetTechnicalGeoReportApiResponse?> GetTechnicalGeoReportOrDefaultAsync(int projectId, string reportType, int id, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetTechnicalGeoReportAsync(projectId, reportType, id, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get a technical GEO report Returns the current status and the full result_data once the report is completed. While it is running, result_data is null and poll_after_seconds tells clients when to check again.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="reportType"></param>
        /// <param name="id">Report id returned by POST /technical_geo_reports or GET /technical_geo_reports</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetTechnicalGeoReportApiResponse"/>&gt;</returns>
        public async Task<IGetTechnicalGeoReportApiResponse> GetTechnicalGeoReportAsync(int projectId, string reportType, int id, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetTechnicalGeoReport(reportType);

                FormatGetTechnicalGeoReport(ref projectId, ref reportType, ref id);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/technical_geo_reports/{id}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/technical_geo_reports/{id}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bid%7D", Uri.EscapeDataString(id.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["project_id"] = ClientUtils.ParameterToString(projectId);
                    parseQueryStringLocalVar["report_type"] = ClientUtils.ParameterToString(reportType);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        GetTechnicalGeoReportApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/technical_geo_reports/{id}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetTechnicalGeoReportDefaultImplementation(apiResponseLocalVar, projectId, reportType, id);

                        Events.ExecuteOnGetTechnicalGeoReport(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetTechnicalGeoReportDefaultImplementation(e, "/technical_geo_reports/{id}", uriBuilderLocalVar.Path, projectId, reportType, id);
                Events.ExecuteOnErrorGetTechnicalGeoReport(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetTechnicalGeoReportApiResponse"/>
        /// </summary>
        public partial class GetTechnicalGeoReportApiResponse : LLMPulse.SDK.Client.ApiResponse, IGetTechnicalGeoReportApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TechnicalGEOReportsApi> Logger { get; }

            /// <summary>
            /// The <see cref="GetTechnicalGeoReportApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetTechnicalGeoReportApiResponse(ILogger<TechnicalGEOReportsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetTechnicalGeoReportApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetTechnicalGeoReportApiResponse(ILogger<TechnicalGEOReportsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatListTechnicalGeoReports(ref int projectId, ref string reportType, ref Option<string> status, ref Option<int> batchId, ref Option<int> page, ref Option<int> perPage);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="reportType"></param>
        /// <param name="status"></param>
        /// <returns></returns>
        private void ValidateListTechnicalGeoReports(string reportType, Option<string> status)
        {
            if (reportType == null)
                throw new ArgumentNullException(nameof(reportType));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="reportType"></param>
        /// <param name="status"></param>
        /// <param name="batchId"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        private void AfterListTechnicalGeoReportsDefaultImplementation(IListTechnicalGeoReportsApiResponse apiResponseLocalVar, int projectId, string reportType, Option<string> status, Option<int> batchId, Option<int> page, Option<int> perPage)
        {
            bool suppressDefaultLog = false;
            AfterListTechnicalGeoReports(ref suppressDefaultLog, apiResponseLocalVar, projectId, reportType, status, batchId, page, perPage);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="reportType"></param>
        /// <param name="status"></param>
        /// <param name="batchId"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        partial void AfterListTechnicalGeoReports(ref bool suppressDefaultLog, IListTechnicalGeoReportsApiResponse apiResponseLocalVar, int projectId, string reportType, Option<string> status, Option<int> batchId, Option<int> page, Option<int> perPage);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="reportType"></param>
        /// <param name="status"></param>
        /// <param name="batchId"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        private void OnErrorListTechnicalGeoReportsDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, string reportType, Option<string> status, Option<int> batchId, Option<int> page, Option<int> perPage)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorListTechnicalGeoReports(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, projectId, reportType, status, batchId, page, perPage);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="projectId"></param>
        /// <param name="reportType"></param>
        /// <param name="status"></param>
        /// <param name="batchId"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        partial void OnErrorListTechnicalGeoReports(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int projectId, string reportType, Option<string> status, Option<int> batchId, Option<int> page, Option<int> perPage);

        /// <summary>
        /// List technical GEO reports Lists reports of one technical GEO type for a project, newest first. Use agent_readiness for the AI/Agent Readiness report.
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="reportType"></param>
        /// <param name="status">Optional status filter; valid values depend on report_type (optional)</param>
        /// <param name="batchId">Optional batch id returned when the report bundle was created (optional)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="perPage"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListTechnicalGeoReportsApiResponse"/>&gt;</returns>
        public async Task<IListTechnicalGeoReportsApiResponse?> ListTechnicalGeoReportsOrDefaultAsync(int projectId, string reportType, Option<string> status = default, Option<int> batchId = default, Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ListTechnicalGeoReportsAsync(projectId, reportType, status, batchId, page, perPage, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// List technical GEO reports Lists reports of one technical GEO type for a project, newest first. Use agent_readiness for the AI/Agent Readiness report.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="projectId">Project ID</param>
        /// <param name="reportType"></param>
        /// <param name="status">Optional status filter; valid values depend on report_type (optional)</param>
        /// <param name="batchId">Optional batch id returned when the report bundle was created (optional)</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="perPage"> (optional, default to 20)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IListTechnicalGeoReportsApiResponse"/>&gt;</returns>
        public async Task<IListTechnicalGeoReportsApiResponse> ListTechnicalGeoReportsAsync(int projectId, string reportType, Option<string> status = default, Option<int> batchId = default, Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateListTechnicalGeoReports(reportType, status);

                FormatListTechnicalGeoReports(ref projectId, ref reportType, ref status, ref batchId, ref page, ref perPage);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/technical_geo_reports"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/technical_geo_reports");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["project_id"] = ClientUtils.ParameterToString(projectId);
                    parseQueryStringLocalVar["report_type"] = ClientUtils.ParameterToString(reportType);

                    if (status.IsSet)
                        parseQueryStringLocalVar["status"] = ClientUtils.ParameterToString(status.Value);

                    if (batchId.IsSet)
                        parseQueryStringLocalVar["batch_id"] = ClientUtils.ParameterToString(batchId.Value);

                    if (page.IsSet)
                        parseQueryStringLocalVar["page"] = ClientUtils.ParameterToString(page.Value);

                    if (perPage.IsSet)
                        parseQueryStringLocalVar["per_page"] = ClientUtils.ParameterToString(perPage.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ListTechnicalGeoReportsApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/technical_geo_reports", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterListTechnicalGeoReportsDefaultImplementation(apiResponseLocalVar, projectId, reportType, status, batchId, page, perPage);

                        Events.ExecuteOnListTechnicalGeoReports(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorListTechnicalGeoReportsDefaultImplementation(e, "/technical_geo_reports", uriBuilderLocalVar.Path, projectId, reportType, status, batchId, page, perPage);
                Events.ExecuteOnErrorListTechnicalGeoReports(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ListTechnicalGeoReportsApiResponse"/>
        /// </summary>
        public partial class ListTechnicalGeoReportsApiResponse : LLMPulse.SDK.Client.ApiResponse, IListTechnicalGeoReportsApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TechnicalGEOReportsApi> Logger { get; }

            /// <summary>
            /// The <see cref="ListTechnicalGeoReportsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListTechnicalGeoReportsApiResponse(ILogger<TechnicalGEOReportsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ListTechnicalGeoReportsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ListTechnicalGeoReportsApiResponse(ILogger<TechnicalGEOReportsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public LLMPulse.SDK.Model.ApiError? UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<LLMPulse.SDK.Model.ApiError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out LLMPulse.SDK.Model.ApiError? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
