// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// CatalogPromptSuggestionsRejectResponse
    /// </summary>
    public partial class CatalogPromptSuggestionsRejectResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CatalogPromptSuggestionsRejectResponse" /> class.
        /// </summary>
        /// <param name="projectId">projectId</param>
        /// <param name="rejected">rejected</param>
        /// <param name="requestId">requestId</param>
        [JsonConstructor]
        public CatalogPromptSuggestionsRejectResponse(int projectId, int rejected, string requestId)
        {
            ProjectId = projectId;
            Rejected = rejected;
            RequestId = requestId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("project_id")]
        public int ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets Rejected
        /// </summary>
        [JsonPropertyName("rejected")]
        public int Rejected { get; set; }

        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>
        [JsonPropertyName("request_id")]
        public string RequestId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CatalogPromptSuggestionsRejectResponse {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Rejected: ").Append(Rejected).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CatalogPromptSuggestionsRejectResponse" />
    /// </summary>
    public partial class CatalogPromptSuggestionsRejectResponseJsonConverter : JsonConverter<CatalogPromptSuggestionsRejectResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CatalogPromptSuggestionsRejectResponseJsonConverter" /> class.
        /// </summary>
        public CatalogPromptSuggestionsRejectResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CatalogPromptSuggestionsRejectResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CatalogPromptSuggestionsRejectResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> projectId = default;
            Option<int?> rejected = default;
            Option<string?> requestId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "project_id":
                            projectId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "rejected":
                            rejected = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "request_id":
                            requestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!projectId.IsSet)
                throw new ArgumentException("Property is required for class CatalogPromptSuggestionsRejectResponse.", nameof(projectId));

            if (!rejected.IsSet)
                throw new ArgumentException("Property is required for class CatalogPromptSuggestionsRejectResponse.", nameof(rejected));

            if (!requestId.IsSet)
                throw new ArgumentException("Property is required for class CatalogPromptSuggestionsRejectResponse.", nameof(requestId));

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class CatalogPromptSuggestionsRejectResponse.");

            if (rejected.IsSet && rejected.Value == null)
                throw new ArgumentNullException(nameof(rejected), "Property is not nullable for class CatalogPromptSuggestionsRejectResponse.");

            if (requestId.IsSet && requestId.Value == null)
                throw new ArgumentNullException(nameof(requestId), "Property is not nullable for class CatalogPromptSuggestionsRejectResponse.");

            return new CatalogPromptSuggestionsRejectResponse(projectId.Value!.Value!, rejected.Value!.Value!, requestId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CatalogPromptSuggestionsRejectResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="catalogPromptSuggestionsRejectResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CatalogPromptSuggestionsRejectResponse catalogPromptSuggestionsRejectResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, catalogPromptSuggestionsRejectResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CatalogPromptSuggestionsRejectResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="catalogPromptSuggestionsRejectResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CatalogPromptSuggestionsRejectResponse catalogPromptSuggestionsRejectResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (catalogPromptSuggestionsRejectResponse.RequestId == null)
                throw new ArgumentNullException(nameof(catalogPromptSuggestionsRejectResponse.RequestId), "Property is required for class CatalogPromptSuggestionsRejectResponse.");

            writer.WriteNumber("project_id", catalogPromptSuggestionsRejectResponse.ProjectId);

            writer.WriteNumber("rejected", catalogPromptSuggestionsRejectResponse.Rejected);

            writer.WriteString("request_id", catalogPromptSuggestionsRejectResponse.RequestId);
        }
    }
}
