// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// CollectionCreateResponse
    /// </summary>
    public partial class CollectionCreateResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionCreateResponse" /> class.
        /// </summary>
        /// <param name="projectId">projectId</param>
        /// <param name="collection">collection</param>
        /// <param name="promptsAttached">Existing prompts attached through prompt_ids</param>
        /// <param name="totalCollections">totalCollections</param>
        /// <param name="requestId">requestId</param>
        [JsonConstructor]
        public CollectionCreateResponse(int projectId, CollectionCreateResponseCollection collection, int promptsAttached, int totalCollections, string requestId)
        {
            ProjectId = projectId;
            Collection = collection;
            PromptsAttached = promptsAttached;
            TotalCollections = totalCollections;
            RequestId = requestId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("project_id")]
        public int ProjectId { get; set; }

        /// <summary>
        /// Gets or Sets Collection
        /// </summary>
        [JsonPropertyName("collection")]
        public CollectionCreateResponseCollection Collection { get; set; }

        /// <summary>
        /// Existing prompts attached through prompt_ids
        /// </summary>
        /// <value>Existing prompts attached through prompt_ids</value>
        [JsonPropertyName("prompts_attached")]
        public int PromptsAttached { get; set; }

        /// <summary>
        /// Gets or Sets TotalCollections
        /// </summary>
        [JsonPropertyName("total_collections")]
        public int TotalCollections { get; set; }

        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>
        [JsonPropertyName("request_id")]
        public string RequestId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CollectionCreateResponse {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Collection: ").Append(Collection).Append("\n");
            sb.Append("  PromptsAttached: ").Append(PromptsAttached).Append("\n");
            sb.Append("  TotalCollections: ").Append(TotalCollections).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CollectionCreateResponse" />
    /// </summary>
    public partial class CollectionCreateResponseJsonConverter : JsonConverter<CollectionCreateResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionCreateResponseJsonConverter" /> class.
        /// </summary>
        public CollectionCreateResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CollectionCreateResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CollectionCreateResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> projectId = default;
            Option<CollectionCreateResponseCollection?> collection = default;
            Option<int?> promptsAttached = default;
            Option<int?> totalCollections = default;
            Option<string?> requestId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "project_id":
                            projectId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "collection":
                            collection = new Option<CollectionCreateResponseCollection?>(JsonSerializer.Deserialize<CollectionCreateResponseCollection>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "prompts_attached":
                            promptsAttached = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_collections":
                            totalCollections = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "request_id":
                            requestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!projectId.IsSet)
                throw new ArgumentException("Property is required for class CollectionCreateResponse.", nameof(projectId));

            if (!collection.IsSet)
                throw new ArgumentException("Property is required for class CollectionCreateResponse.", nameof(collection));

            if (!promptsAttached.IsSet)
                throw new ArgumentException("Property is required for class CollectionCreateResponse.", nameof(promptsAttached));

            if (!totalCollections.IsSet)
                throw new ArgumentException("Property is required for class CollectionCreateResponse.", nameof(totalCollections));

            if (!requestId.IsSet)
                throw new ArgumentException("Property is required for class CollectionCreateResponse.", nameof(requestId));

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class CollectionCreateResponse.");

            if (collection.IsSet && collection.Value == null)
                throw new ArgumentNullException(nameof(collection), "Property is not nullable for class CollectionCreateResponse.");

            if (promptsAttached.IsSet && promptsAttached.Value == null)
                throw new ArgumentNullException(nameof(promptsAttached), "Property is not nullable for class CollectionCreateResponse.");

            if (totalCollections.IsSet && totalCollections.Value == null)
                throw new ArgumentNullException(nameof(totalCollections), "Property is not nullable for class CollectionCreateResponse.");

            if (requestId.IsSet && requestId.Value == null)
                throw new ArgumentNullException(nameof(requestId), "Property is not nullable for class CollectionCreateResponse.");

            return new CollectionCreateResponse(projectId.Value!.Value!, collection.Value!, promptsAttached.Value!.Value!, totalCollections.Value!.Value!, requestId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CollectionCreateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="collectionCreateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CollectionCreateResponse collectionCreateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, collectionCreateResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CollectionCreateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="collectionCreateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CollectionCreateResponse collectionCreateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (collectionCreateResponse.Collection == null)
                throw new ArgumentNullException(nameof(collectionCreateResponse.Collection), "Property is required for class CollectionCreateResponse.");

            if (collectionCreateResponse.RequestId == null)
                throw new ArgumentNullException(nameof(collectionCreateResponse.RequestId), "Property is required for class CollectionCreateResponse.");

            writer.WriteNumber("project_id", collectionCreateResponse.ProjectId);

            writer.WritePropertyName("collection");
            JsonSerializer.Serialize(writer, collectionCreateResponse.Collection, jsonSerializerOptions);
            writer.WriteNumber("prompts_attached", collectionCreateResponse.PromptsAttached);

            writer.WriteNumber("total_collections", collectionCreateResponse.TotalCollections);

            writer.WriteString("request_id", collectionCreateResponse.RequestId);
        }
    }
}
