// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// Competitor
    /// </summary>
    public partial class Competitor : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Competitor" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="domain">Bare (scheme-less) domain. Null only on the own-brand row (include_project_brand&#x3D;true) when the project has no URL.</param>
        /// <param name="matchingNames">Alternative names matched as this competitor. Absent on the own-brand row</param>
        /// <param name="citationMatchMode">citationMatchMode</param>
        /// <param name="citationMatchPath">Set only when citation_match_mode is path_prefix</param>
        /// <param name="actorType">Only present when include_project_brand&#x3D;true</param>
        /// <param name="isOwn">Only present when include_project_brand&#x3D;true</param>
        [JsonConstructor]
        public Competitor(Option<int?> id = default, Option<string?> name = default, Option<string?> domain = default, Option<List<string>?> matchingNames = default, Option<CitationMatchMode?> citationMatchMode = default, Option<string?> citationMatchPath = default, Option<ActorTypeEnum?> actorType = default, Option<bool?> isOwn = default)
        {
            IdOption = id;
            NameOption = name;
            DomainOption = domain;
            MatchingNamesOption = matchingNames;
            CitationMatchModeOption = citationMatchMode;
            CitationMatchPathOption = citationMatchPath;
            ActorTypeOption = actorType;
            IsOwnOption = isOwn;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of CitationMatchMode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CitationMatchMode?> CitationMatchModeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CitationMatchMode
        /// </summary>
        [JsonPropertyName("citation_match_mode")]
        public CitationMatchMode? CitationMatchMode { get { return this.CitationMatchModeOption.Value; } set { this.CitationMatchModeOption = new(value); } }

        /// <summary>
        /// Only present when include_project_brand&#x3D;true
        /// </summary>
        /// <value>Only present when include_project_brand&#x3D;true</value>
        public enum ActorTypeEnum
        {
            /// <summary>
            /// Enum Project for value: project
            /// </summary>
            Project = 1,

            /// <summary>
            /// Enum Competitor for value: competitor
            /// </summary>
            Competitor = 2
        }

        /// <summary>
        /// Returns a <see cref="ActorTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ActorTypeEnum ActorTypeEnumFromString(string value)
        {
            if (value.Equals("project"))
                return ActorTypeEnum.Project;

            if (value.Equals("competitor"))
                return ActorTypeEnum.Competitor;

            throw new NotImplementedException($"Could not convert value to type ActorTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ActorTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ActorTypeEnum? ActorTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("project"))
                return ActorTypeEnum.Project;

            if (value.Equals("competitor"))
                return ActorTypeEnum.Competitor;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ActorTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ActorTypeEnumToJsonValue(ActorTypeEnum? value)
        {
            if (value == ActorTypeEnum.Project)
                return "project";

            if (value == ActorTypeEnum.Competitor)
                return "competitor";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of ActorType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ActorTypeEnum?> ActorTypeOption { get; private set; }

        /// <summary>
        /// Only present when include_project_brand&#x3D;true
        /// </summary>
        /// <value>Only present when include_project_brand&#x3D;true</value>
        [JsonPropertyName("actor_type")]
        public ActorTypeEnum? ActorType { get { return this.ActorTypeOption.Value; } set { this.ActorTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Domain
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DomainOption { get; private set; }

        /// <summary>
        /// Bare (scheme-less) domain. Null only on the own-brand row (include_project_brand&#x3D;true) when the project has no URL.
        /// </summary>
        /// <value>Bare (scheme-less) domain. Null only on the own-brand row (include_project_brand&#x3D;true) when the project has no URL.</value>
        [JsonPropertyName("domain")]
        public string? Domain { get { return this.DomainOption.Value; } set { this.DomainOption = new(value); } }

        /// <summary>
        /// Used to track the state of MatchingNames
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> MatchingNamesOption { get; private set; }

        /// <summary>
        /// Alternative names matched as this competitor. Absent on the own-brand row
        /// </summary>
        /// <value>Alternative names matched as this competitor. Absent on the own-brand row</value>
        [JsonPropertyName("matching_names")]
        public List<string>? MatchingNames { get { return this.MatchingNamesOption.Value; } set { this.MatchingNamesOption = new(value); } }

        /// <summary>
        /// Used to track the state of CitationMatchPath
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CitationMatchPathOption { get; private set; }

        /// <summary>
        /// Set only when citation_match_mode is path_prefix
        /// </summary>
        /// <value>Set only when citation_match_mode is path_prefix</value>
        [JsonPropertyName("citation_match_path")]
        public string? CitationMatchPath { get { return this.CitationMatchPathOption.Value; } set { this.CitationMatchPathOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsOwn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsOwnOption { get; private set; }

        /// <summary>
        /// Only present when include_project_brand&#x3D;true
        /// </summary>
        /// <value>Only present when include_project_brand&#x3D;true</value>
        [JsonPropertyName("is_own")]
        public bool? IsOwn { get { return this.IsOwnOption.Value; } set { this.IsOwnOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Competitor {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  MatchingNames: ").Append(MatchingNames).Append("\n");
            sb.Append("  CitationMatchMode: ").Append(CitationMatchMode).Append("\n");
            sb.Append("  CitationMatchPath: ").Append(CitationMatchPath).Append("\n");
            sb.Append("  ActorType: ").Append(ActorType).Append("\n");
            sb.Append("  IsOwn: ").Append(IsOwn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Competitor" />
    /// </summary>
    public partial class CompetitorJsonConverter : JsonConverter<Competitor>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CompetitorJsonConverter" /> class.
        /// </summary>
        public CompetitorJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Competitor" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Competitor Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<string?> domain = default;
            Option<List<string>?> matchingNames = default;
            Option<CitationMatchMode?> citationMatchMode = default;
            Option<string?> citationMatchPath = default;
            Option<Competitor.ActorTypeEnum?> actorType = default;
            Option<bool?> isOwn = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "domain":
                            domain = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "matching_names":
                            matchingNames = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "citation_match_mode":
                            citationMatchMode = new Option<CitationMatchMode?>(JsonSerializer.Deserialize<CitationMatchMode?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "citation_match_path":
                            citationMatchPath = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "actor_type":
                            string? actorTypeRawValue = utf8JsonReader.GetString();
                            if (actorTypeRawValue != null)
                                actorType = new Option<Competitor.ActorTypeEnum?>(Competitor.ActorTypeEnumFromStringOrDefault(actorTypeRawValue));
                            break;
                        case "is_own":
                            isOwn = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Competitor.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Competitor.");

            if (matchingNames.IsSet && matchingNames.Value == null)
                throw new ArgumentNullException(nameof(matchingNames), "Property is not nullable for class Competitor.");

            if (citationMatchMode.IsSet && citationMatchMode.Value == null)
                throw new ArgumentNullException(nameof(citationMatchMode), "Property is not nullable for class Competitor.");

            if (actorType.IsSet && actorType.Value == null)
                throw new ArgumentNullException(nameof(actorType), "Property is not nullable for class Competitor.");

            if (isOwn.IsSet && isOwn.Value == null)
                throw new ArgumentNullException(nameof(isOwn), "Property is not nullable for class Competitor.");

            return new Competitor(id, name, domain, matchingNames, citationMatchMode, citationMatchPath, actorType, isOwn);
        }

        /// <summary>
        /// Serializes a <see cref="Competitor" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="competitor"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Competitor competitor, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, competitor, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Competitor" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="competitor"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Competitor competitor, JsonSerializerOptions jsonSerializerOptions)
        {
            if (competitor.NameOption.IsSet && competitor.Name == null)
                throw new ArgumentNullException(nameof(competitor.Name), "Property is required for class Competitor.");

            if (competitor.MatchingNamesOption.IsSet && competitor.MatchingNames == null)
                throw new ArgumentNullException(nameof(competitor.MatchingNames), "Property is required for class Competitor.");

            if (competitor.IdOption.IsSet)
                writer.WriteNumber("id", competitor.IdOption.Value!.Value);

            if (competitor.NameOption.IsSet)
                writer.WriteString("name", competitor.Name);

            if (competitor.DomainOption.IsSet)
                if (competitor.DomainOption.Value != null)
                    writer.WriteString("domain", competitor.Domain);
                else
                    writer.WriteNull("domain");

            if (competitor.MatchingNamesOption.IsSet)
            {
                writer.WritePropertyName("matching_names");
                JsonSerializer.Serialize(writer, competitor.MatchingNames, jsonSerializerOptions);
            }
            if (competitor.CitationMatchModeOption.IsSet)
            {
                var citationMatchModeRawValue = CitationMatchModeValueConverter.ToJsonValue(competitor.CitationMatchMode!.Value);
                writer.WriteString("citation_match_mode", citationMatchModeRawValue);
            }
            if (competitor.CitationMatchPathOption.IsSet)
                if (competitor.CitationMatchPathOption.Value != null)
                    writer.WriteString("citation_match_path", competitor.CitationMatchPath);
                else
                    writer.WriteNull("citation_match_path");

            var actorTypeRawValue = Competitor.ActorTypeEnumToJsonValue(competitor.ActorTypeOption.Value!.Value);
            writer.WriteString("actor_type", actorTypeRawValue);
            if (competitor.IsOwnOption.IsSet)
                writer.WriteBoolean("is_own", competitor.IsOwnOption.Value!.Value);
        }
    }
}
