// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// CreateProjectDraftRequest
    /// </summary>
    public partial class CreateProjectDraftRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProjectDraftRequest" /> class.
        /// </summary>
        /// <param name="websiteUrl">Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.</param>
        /// <param name="mainCountry">mainCountry</param>
        /// <param name="mainLanguage">mainLanguage</param>
        /// <param name="useSubdomain">useSubdomain (default to false)</param>
        /// <param name="suggest">suggest (default to true)</param>
        /// <param name="executePromptsImmediately">executePromptsImmediately (default to true)</param>
        [JsonConstructor]
        public CreateProjectDraftRequest(string websiteUrl, string mainCountry, string mainLanguage, Option<bool?> useSubdomain = default, Option<bool?> suggest = default, Option<bool?> executePromptsImmediately = default)
        {
            WebsiteUrl = websiteUrl;
            MainCountry = mainCountry;
            MainLanguage = mainLanguage;
            UseSubdomainOption = useSubdomain;
            SuggestOption = suggest;
            ExecutePromptsImmediatelyOption = executePromptsImmediately;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
        /// </summary>
        /// <value>Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.</value>
        [JsonPropertyName("website_url")]
        public string WebsiteUrl { get; set; }

        /// <summary>
        /// Gets or Sets MainCountry
        /// </summary>
        [JsonPropertyName("main_country")]
        public string MainCountry { get; set; }

        /// <summary>
        /// Gets or Sets MainLanguage
        /// </summary>
        [JsonPropertyName("main_language")]
        public string MainLanguage { get; set; }

        /// <summary>
        /// Used to track the state of UseSubdomain
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UseSubdomainOption { get; private set; }

        /// <summary>
        /// Gets or Sets UseSubdomain
        /// </summary>
        [JsonPropertyName("use_subdomain")]
        public bool? UseSubdomain { get { return this.UseSubdomainOption.Value; } set { this.UseSubdomainOption = new(value); } }

        /// <summary>
        /// Used to track the state of Suggest
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SuggestOption { get; private set; }

        /// <summary>
        /// Gets or Sets Suggest
        /// </summary>
        [JsonPropertyName("suggest")]
        public bool? Suggest { get { return this.SuggestOption.Value; } set { this.SuggestOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExecutePromptsImmediately
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ExecutePromptsImmediatelyOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExecutePromptsImmediately
        /// </summary>
        [JsonPropertyName("execute_prompts_immediately")]
        public bool? ExecutePromptsImmediately { get { return this.ExecutePromptsImmediatelyOption.Value; } set { this.ExecutePromptsImmediatelyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateProjectDraftRequest {\n");
            sb.Append("  WebsiteUrl: ").Append(WebsiteUrl).Append("\n");
            sb.Append("  MainCountry: ").Append(MainCountry).Append("\n");
            sb.Append("  MainLanguage: ").Append(MainLanguage).Append("\n");
            sb.Append("  UseSubdomain: ").Append(UseSubdomain).Append("\n");
            sb.Append("  Suggest: ").Append(Suggest).Append("\n");
            sb.Append("  ExecutePromptsImmediately: ").Append(ExecutePromptsImmediately).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateProjectDraftRequest" />
    /// </summary>
    public partial class CreateProjectDraftRequestJsonConverter : JsonConverter<CreateProjectDraftRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProjectDraftRequestJsonConverter" /> class.
        /// </summary>
        public CreateProjectDraftRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateProjectDraftRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateProjectDraftRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> websiteUrl = default;
            Option<string?> mainCountry = default;
            Option<string?> mainLanguage = default;
            Option<bool?> useSubdomain = default;
            Option<bool?> suggest = default;
            Option<bool?> executePromptsImmediately = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "website_url":
                            websiteUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "main_country":
                            mainCountry = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "main_language":
                            mainLanguage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "use_subdomain":
                            useSubdomain = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "suggest":
                            suggest = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "execute_prompts_immediately":
                            executePromptsImmediately = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!websiteUrl.IsSet)
                throw new ArgumentException("Property is required for class CreateProjectDraftRequest.", nameof(websiteUrl));

            if (!mainCountry.IsSet)
                throw new ArgumentException("Property is required for class CreateProjectDraftRequest.", nameof(mainCountry));

            if (!mainLanguage.IsSet)
                throw new ArgumentException("Property is required for class CreateProjectDraftRequest.", nameof(mainLanguage));

            if (websiteUrl.IsSet && websiteUrl.Value == null)
                throw new ArgumentNullException(nameof(websiteUrl), "Property is not nullable for class CreateProjectDraftRequest.");

            if (mainCountry.IsSet && mainCountry.Value == null)
                throw new ArgumentNullException(nameof(mainCountry), "Property is not nullable for class CreateProjectDraftRequest.");

            if (mainLanguage.IsSet && mainLanguage.Value == null)
                throw new ArgumentNullException(nameof(mainLanguage), "Property is not nullable for class CreateProjectDraftRequest.");

            if (useSubdomain.IsSet && useSubdomain.Value == null)
                throw new ArgumentNullException(nameof(useSubdomain), "Property is not nullable for class CreateProjectDraftRequest.");

            if (suggest.IsSet && suggest.Value == null)
                throw new ArgumentNullException(nameof(suggest), "Property is not nullable for class CreateProjectDraftRequest.");

            if (executePromptsImmediately.IsSet && executePromptsImmediately.Value == null)
                throw new ArgumentNullException(nameof(executePromptsImmediately), "Property is not nullable for class CreateProjectDraftRequest.");

            return new CreateProjectDraftRequest(websiteUrl.Value!, mainCountry.Value!, mainLanguage.Value!, useSubdomain, suggest, executePromptsImmediately);
        }

        /// <summary>
        /// Serializes a <see cref="CreateProjectDraftRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createProjectDraftRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateProjectDraftRequest createProjectDraftRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createProjectDraftRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateProjectDraftRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createProjectDraftRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateProjectDraftRequest createProjectDraftRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createProjectDraftRequest.WebsiteUrl == null)
                throw new ArgumentNullException(nameof(createProjectDraftRequest.WebsiteUrl), "Property is required for class CreateProjectDraftRequest.");

            if (createProjectDraftRequest.MainCountry == null)
                throw new ArgumentNullException(nameof(createProjectDraftRequest.MainCountry), "Property is required for class CreateProjectDraftRequest.");

            if (createProjectDraftRequest.MainLanguage == null)
                throw new ArgumentNullException(nameof(createProjectDraftRequest.MainLanguage), "Property is required for class CreateProjectDraftRequest.");

            writer.WriteString("website_url", createProjectDraftRequest.WebsiteUrl);

            writer.WriteString("main_country", createProjectDraftRequest.MainCountry);

            writer.WriteString("main_language", createProjectDraftRequest.MainLanguage);

            if (createProjectDraftRequest.UseSubdomainOption.IsSet)
                writer.WriteBoolean("use_subdomain", createProjectDraftRequest.UseSubdomainOption.Value!.Value);

            if (createProjectDraftRequest.SuggestOption.IsSet)
                writer.WriteBoolean("suggest", createProjectDraftRequest.SuggestOption.Value!.Value);

            if (createProjectDraftRequest.ExecutePromptsImmediatelyOption.IsSet)
                writer.WriteBoolean("execute_prompts_immediately", createProjectDraftRequest.ExecutePromptsImmediatelyOption.Value!.Value);
        }
    }
}
