// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// GeoAuditUpdateRequest
    /// </summary>
    public partial class GeoAuditUpdateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoAuditUpdateRequest" /> class.
        /// </summary>
        /// <param name="projectId">projectId</param>
        /// <param name="cadence">cadence</param>
        /// <param name="scheduleDay">Weekly: 0 (Sunday) to 6. Monthly: 1 to 28.</param>
        /// <param name="scheduleHour">Hour of the day, 0 to 23, in the audit time zone</param>
        /// <param name="status">paused stops scheduled runs, active resumes them, archived is the same as DELETE</param>
        /// <param name="emailAlerts">emailAlerts</param>
        [JsonConstructor]
        public GeoAuditUpdateRequest(Option<int?> projectId = default, Option<CadenceEnum?> cadence = default, Option<int?> scheduleDay = default, Option<int?> scheduleHour = default, Option<StatusEnum?> status = default, Option<bool?> emailAlerts = default)
        {
            ProjectIdOption = projectId;
            CadenceOption = cadence;
            ScheduleDayOption = scheduleDay;
            ScheduleHourOption = scheduleHour;
            StatusOption = status;
            EmailAlertsOption = emailAlerts;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Cadence
        /// </summary>
        public enum CadenceEnum
        {
            /// <summary>
            /// Enum Once for value: once
            /// </summary>
            Once = 1,

            /// <summary>
            /// Enum Weekly for value: weekly
            /// </summary>
            Weekly = 2,

            /// <summary>
            /// Enum Monthly for value: monthly
            /// </summary>
            Monthly = 3
        }

        /// <summary>
        /// Returns a <see cref="CadenceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CadenceEnum CadenceEnumFromString(string value)
        {
            if (value.Equals("once"))
                return CadenceEnum.Once;

            if (value.Equals("weekly"))
                return CadenceEnum.Weekly;

            if (value.Equals("monthly"))
                return CadenceEnum.Monthly;

            throw new NotImplementedException($"Could not convert value to type CadenceEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CadenceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CadenceEnum? CadenceEnumFromStringOrDefault(string value)
        {
            if (value.Equals("once"))
                return CadenceEnum.Once;

            if (value.Equals("weekly"))
                return CadenceEnum.Weekly;

            if (value.Equals("monthly"))
                return CadenceEnum.Monthly;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CadenceEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CadenceEnumToJsonValue(CadenceEnum? value)
        {
            if (value == CadenceEnum.Once)
                return "once";

            if (value == CadenceEnum.Weekly)
                return "weekly";

            if (value == CadenceEnum.Monthly)
                return "monthly";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Cadence
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CadenceEnum?> CadenceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cadence
        /// </summary>
        [JsonPropertyName("cadence")]
        public CadenceEnum? Cadence { get { return this.CadenceOption.Value; } set { this.CadenceOption = new(value); } }

        /// <summary>
        /// paused stops scheduled runs, active resumes them, archived is the same as DELETE
        /// </summary>
        /// <value>paused stops scheduled runs, active resumes them, archived is the same as DELETE</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            Active = 1,

            /// <summary>
            /// Enum Paused for value: paused
            /// </summary>
            Paused = 2,

            /// <summary>
            /// Enum Archived for value: archived
            /// </summary>
            Archived = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("paused"))
                return StatusEnum.Paused;

            if (value.Equals("archived"))
                return StatusEnum.Archived;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("paused"))
                return StatusEnum.Paused;

            if (value.Equals("archived"))
                return StatusEnum.Archived;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Active)
                return "active";

            if (value == StatusEnum.Paused)
                return "paused";

            if (value == StatusEnum.Archived)
                return "archived";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// paused stops scheduled runs, active resumes them, archived is the same as DELETE
        /// </summary>
        /// <value>paused stops scheduled runs, active resumes them, archived is the same as DELETE</value>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProjectId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ProjectIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("project_id")]
        public int? ProjectId { get { return this.ProjectIdOption.Value; } set { this.ProjectIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ScheduleDay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ScheduleDayOption { get; private set; }

        /// <summary>
        /// Weekly: 0 (Sunday) to 6. Monthly: 1 to 28.
        /// </summary>
        /// <value>Weekly: 0 (Sunday) to 6. Monthly: 1 to 28.</value>
        [JsonPropertyName("schedule_day")]
        public int? ScheduleDay { get { return this.ScheduleDayOption.Value; } set { this.ScheduleDayOption = new(value); } }

        /// <summary>
        /// Used to track the state of ScheduleHour
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ScheduleHourOption { get; private set; }

        /// <summary>
        /// Hour of the day, 0 to 23, in the audit time zone
        /// </summary>
        /// <value>Hour of the day, 0 to 23, in the audit time zone</value>
        [JsonPropertyName("schedule_hour")]
        public int? ScheduleHour { get { return this.ScheduleHourOption.Value; } set { this.ScheduleHourOption = new(value); } }

        /// <summary>
        /// Used to track the state of EmailAlerts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EmailAlertsOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmailAlerts
        /// </summary>
        [JsonPropertyName("email_alerts")]
        public bool? EmailAlerts { get { return this.EmailAlertsOption.Value; } set { this.EmailAlertsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoAuditUpdateRequest {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Cadence: ").Append(Cadence).Append("\n");
            sb.Append("  ScheduleDay: ").Append(ScheduleDay).Append("\n");
            sb.Append("  ScheduleHour: ").Append(ScheduleHour).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  EmailAlerts: ").Append(EmailAlerts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GeoAuditUpdateRequest" />
    /// </summary>
    public partial class GeoAuditUpdateRequestJsonConverter : JsonConverter<GeoAuditUpdateRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GeoAuditUpdateRequestJsonConverter" /> class.
        /// </summary>
        public GeoAuditUpdateRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GeoAuditUpdateRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GeoAuditUpdateRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> projectId = default;
            Option<GeoAuditUpdateRequest.CadenceEnum?> cadence = default;
            Option<int?> scheduleDay = default;
            Option<int?> scheduleHour = default;
            Option<GeoAuditUpdateRequest.StatusEnum?> status = default;
            Option<bool?> emailAlerts = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "project_id":
                            projectId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "cadence":
                            string? cadenceRawValue = utf8JsonReader.GetString();
                            if (cadenceRawValue != null)
                                cadence = new Option<GeoAuditUpdateRequest.CadenceEnum?>(GeoAuditUpdateRequest.CadenceEnumFromStringOrDefault(cadenceRawValue));
                            break;
                        case "schedule_day":
                            scheduleDay = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "schedule_hour":
                            scheduleHour = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<GeoAuditUpdateRequest.StatusEnum?>(GeoAuditUpdateRequest.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "email_alerts":
                            emailAlerts = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class GeoAuditUpdateRequest.");

            if (cadence.IsSet && cadence.Value == null)
                throw new ArgumentNullException(nameof(cadence), "Property is not nullable for class GeoAuditUpdateRequest.");

            if (scheduleDay.IsSet && scheduleDay.Value == null)
                throw new ArgumentNullException(nameof(scheduleDay), "Property is not nullable for class GeoAuditUpdateRequest.");

            if (scheduleHour.IsSet && scheduleHour.Value == null)
                throw new ArgumentNullException(nameof(scheduleHour), "Property is not nullable for class GeoAuditUpdateRequest.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class GeoAuditUpdateRequest.");

            if (emailAlerts.IsSet && emailAlerts.Value == null)
                throw new ArgumentNullException(nameof(emailAlerts), "Property is not nullable for class GeoAuditUpdateRequest.");

            return new GeoAuditUpdateRequest(projectId, cadence, scheduleDay, scheduleHour, status, emailAlerts);
        }

        /// <summary>
        /// Serializes a <see cref="GeoAuditUpdateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geoAuditUpdateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GeoAuditUpdateRequest geoAuditUpdateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, geoAuditUpdateRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GeoAuditUpdateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geoAuditUpdateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GeoAuditUpdateRequest geoAuditUpdateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (geoAuditUpdateRequest.ProjectIdOption.IsSet)
                writer.WriteNumber("project_id", geoAuditUpdateRequest.ProjectIdOption.Value!.Value);

            var cadenceRawValue = GeoAuditUpdateRequest.CadenceEnumToJsonValue(geoAuditUpdateRequest.CadenceOption.Value!.Value);
            writer.WriteString("cadence", cadenceRawValue);
            if (geoAuditUpdateRequest.ScheduleDayOption.IsSet)
                writer.WriteNumber("schedule_day", geoAuditUpdateRequest.ScheduleDayOption.Value!.Value);

            if (geoAuditUpdateRequest.ScheduleHourOption.IsSet)
                writer.WriteNumber("schedule_hour", geoAuditUpdateRequest.ScheduleHourOption.Value!.Value);

            var statusRawValue = GeoAuditUpdateRequest.StatusEnumToJsonValue(geoAuditUpdateRequest.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (geoAuditUpdateRequest.EmailAlertsOption.IsSet)
                writer.WriteBoolean("email_alerts", geoAuditUpdateRequest.EmailAlertsOption.Value!.Value);
        }
    }
}
