// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// GeoAuditCreateRequest
    /// </summary>
    public partial class GeoAuditCreateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoAuditCreateRequest" /> class.
        /// </summary>
        /// <param name="projectId">projectId</param>
        /// <param name="target">The domain (site-wide types) or page URL to audit</param>
        /// <param name="auditTypes">One or more audit types; each becomes its own audit and starts its first run</param>
        /// <param name="cadence">once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits</param>
        [JsonConstructor]
        public GeoAuditCreateRequest(int projectId, string target, List<GeoAuditCreateRequest.AuditTypesEnum> auditTypes, Option<CadenceEnum?> cadence = default)
        {
            ProjectId = projectId;
            Target = target;
            AuditTypes = auditTypes;
            CadenceOption = cadence;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines AuditTypes
        /// </summary>
        public enum AuditTypesEnum
        {
            /// <summary>
            /// Enum AgentReadiness for value: agent_readiness
            /// </summary>
            AgentReadiness = 1,

            /// <summary>
            /// Enum RobotsTxt for value: robots_txt
            /// </summary>
            RobotsTxt = 2,

            /// <summary>
            /// Enum Crawlability for value: crawlability
            /// </summary>
            Crawlability = 3,

            /// <summary>
            /// Enum Schema for value: schema
            /// </summary>
            Schema = 4,

            /// <summary>
            /// Enum ContentReadiness for value: content_readiness
            /// </summary>
            ContentReadiness = 5,

            /// <summary>
            /// Enum Discoverability for value: discoverability
            /// </summary>
            Discoverability = 6,

            /// <summary>
            /// Enum SiteStructure for value: site_structure
            /// </summary>
            SiteStructure = 7
        }

        /// <summary>
        /// Returns a <see cref="AuditTypesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static AuditTypesEnum AuditTypesEnumFromString(string value)
        {
            if (value.Equals("agent_readiness"))
                return AuditTypesEnum.AgentReadiness;

            if (value.Equals("robots_txt"))
                return AuditTypesEnum.RobotsTxt;

            if (value.Equals("crawlability"))
                return AuditTypesEnum.Crawlability;

            if (value.Equals("schema"))
                return AuditTypesEnum.Schema;

            if (value.Equals("content_readiness"))
                return AuditTypesEnum.ContentReadiness;

            if (value.Equals("discoverability"))
                return AuditTypesEnum.Discoverability;

            if (value.Equals("site_structure"))
                return AuditTypesEnum.SiteStructure;

            throw new NotImplementedException($"Could not convert value to type AuditTypesEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="AuditTypesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AuditTypesEnum? AuditTypesEnumFromStringOrDefault(string value)
        {
            if (value.Equals("agent_readiness"))
                return AuditTypesEnum.AgentReadiness;

            if (value.Equals("robots_txt"))
                return AuditTypesEnum.RobotsTxt;

            if (value.Equals("crawlability"))
                return AuditTypesEnum.Crawlability;

            if (value.Equals("schema"))
                return AuditTypesEnum.Schema;

            if (value.Equals("content_readiness"))
                return AuditTypesEnum.ContentReadiness;

            if (value.Equals("discoverability"))
                return AuditTypesEnum.Discoverability;

            if (value.Equals("site_structure"))
                return AuditTypesEnum.SiteStructure;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="AuditTypesEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string AuditTypesEnumToJsonValue(AuditTypesEnum? value)
        {
            if (value == AuditTypesEnum.AgentReadiness)
                return "agent_readiness";

            if (value == AuditTypesEnum.RobotsTxt)
                return "robots_txt";

            if (value == AuditTypesEnum.Crawlability)
                return "crawlability";

            if (value == AuditTypesEnum.Schema)
                return "schema";

            if (value == AuditTypesEnum.ContentReadiness)
                return "content_readiness";

            if (value == AuditTypesEnum.Discoverability)
                return "discoverability";

            if (value == AuditTypesEnum.SiteStructure)
                return "site_structure";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits
        /// </summary>
        /// <value>once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits</value>
        public enum CadenceEnum
        {
            /// <summary>
            /// Enum Once for value: once
            /// </summary>
            Once = 1,

            /// <summary>
            /// Enum Weekly for value: weekly
            /// </summary>
            Weekly = 2,

            /// <summary>
            /// Enum Monthly for value: monthly
            /// </summary>
            Monthly = 3
        }

        /// <summary>
        /// Returns a <see cref="CadenceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static CadenceEnum CadenceEnumFromString(string value)
        {
            if (value.Equals("once"))
                return CadenceEnum.Once;

            if (value.Equals("weekly"))
                return CadenceEnum.Weekly;

            if (value.Equals("monthly"))
                return CadenceEnum.Monthly;

            throw new NotImplementedException($"Could not convert value to type CadenceEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="CadenceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CadenceEnum? CadenceEnumFromStringOrDefault(string value)
        {
            if (value.Equals("once"))
                return CadenceEnum.Once;

            if (value.Equals("weekly"))
                return CadenceEnum.Weekly;

            if (value.Equals("monthly"))
                return CadenceEnum.Monthly;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CadenceEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string CadenceEnumToJsonValue(CadenceEnum? value)
        {
            if (value == CadenceEnum.Once)
                return "once";

            if (value == CadenceEnum.Weekly)
                return "weekly";

            if (value == CadenceEnum.Monthly)
                return "monthly";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Cadence
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CadenceEnum?> CadenceOption { get; private set; }

        /// <summary>
        /// once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits
        /// </summary>
        /// <value>once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits</value>
        [JsonPropertyName("cadence")]
        public CadenceEnum? Cadence { get { return this.CadenceOption.Value; } set { this.CadenceOption = new(value); } }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("project_id")]
        public int ProjectId { get; set; }

        /// <summary>
        /// The domain (site-wide types) or page URL to audit
        /// </summary>
        /// <value>The domain (site-wide types) or page URL to audit</value>
        [JsonPropertyName("target")]
        public string Target { get; set; }

        /// <summary>
        /// One or more audit types; each becomes its own audit and starts its first run
        /// </summary>
        /// <value>One or more audit types; each becomes its own audit and starts its first run</value>
        [JsonPropertyName("audit_types")]
        public List<GeoAuditCreateRequest.AuditTypesEnum> AuditTypes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoAuditCreateRequest {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  AuditTypes: ").Append(AuditTypes).Append("\n");
            sb.Append("  Cadence: ").Append(Cadence).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GeoAuditCreateRequest" />
    /// </summary>
    public partial class GeoAuditCreateRequestJsonConverter : JsonConverter<GeoAuditCreateRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GeoAuditCreateRequestJsonConverter" /> class.
        /// </summary>
        public GeoAuditCreateRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GeoAuditCreateRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GeoAuditCreateRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> projectId = default;
            Option<string?> target = default;
            Option<List<GeoAuditCreateRequest.AuditTypesEnum>?> auditTypes = default;
            Option<GeoAuditCreateRequest.CadenceEnum?> cadence = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "project_id":
                            projectId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "target":
                            target = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "audit_types":
                            auditTypes = new Option<List<GeoAuditCreateRequest.AuditTypesEnum>?>(JsonSerializer.Deserialize<List<GeoAuditCreateRequest.AuditTypesEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cadence":
                            string? cadenceRawValue = utf8JsonReader.GetString();
                            if (cadenceRawValue != null)
                                cadence = new Option<GeoAuditCreateRequest.CadenceEnum?>(GeoAuditCreateRequest.CadenceEnumFromStringOrDefault(cadenceRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!projectId.IsSet)
                throw new ArgumentException("Property is required for class GeoAuditCreateRequest.", nameof(projectId));

            if (!target.IsSet)
                throw new ArgumentException("Property is required for class GeoAuditCreateRequest.", nameof(target));

            if (!auditTypes.IsSet)
                throw new ArgumentException("Property is required for class GeoAuditCreateRequest.", nameof(auditTypes));

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class GeoAuditCreateRequest.");

            if (target.IsSet && target.Value == null)
                throw new ArgumentNullException(nameof(target), "Property is not nullable for class GeoAuditCreateRequest.");

            if (auditTypes.IsSet && auditTypes.Value == null)
                throw new ArgumentNullException(nameof(auditTypes), "Property is not nullable for class GeoAuditCreateRequest.");

            if (cadence.IsSet && cadence.Value == null)
                throw new ArgumentNullException(nameof(cadence), "Property is not nullable for class GeoAuditCreateRequest.");

            return new GeoAuditCreateRequest(projectId.Value!.Value!, target.Value!, auditTypes.Value!, cadence);
        }

        /// <summary>
        /// Serializes a <see cref="GeoAuditCreateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geoAuditCreateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GeoAuditCreateRequest geoAuditCreateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, geoAuditCreateRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GeoAuditCreateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geoAuditCreateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GeoAuditCreateRequest geoAuditCreateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (geoAuditCreateRequest.Target == null)
                throw new ArgumentNullException(nameof(geoAuditCreateRequest.Target), "Property is required for class GeoAuditCreateRequest.");

            if (geoAuditCreateRequest.AuditTypes == null)
                throw new ArgumentNullException(nameof(geoAuditCreateRequest.AuditTypes), "Property is required for class GeoAuditCreateRequest.");

            writer.WriteNumber("project_id", geoAuditCreateRequest.ProjectId);

            writer.WriteString("target", geoAuditCreateRequest.Target);

            writer.WritePropertyName("audit_types");
            JsonSerializer.Serialize(writer, geoAuditCreateRequest.AuditTypes, jsonSerializerOptions);
            var cadenceRawValue = GeoAuditCreateRequest.CadenceEnumToJsonValue(geoAuditCreateRequest.CadenceOption.Value!.Value);
            writer.WriteString("cadence", cadenceRawValue);
        }
    }
}
