// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// GeoAuditRunResponse
    /// </summary>
    public partial class GeoAuditRunResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoAuditRunResponse" /> class.
        /// </summary>
        /// <param name="sequence">Run number within the audit, starting at 1</param>
        /// <param name="status">status</param>
        /// <param name="trigger">trigger</param>
        /// <param name="score">score</param>
        /// <param name="grade">grade</param>
        /// <param name="scoreDelta">Score change against the previous completed run</param>
        /// <param name="comparableToPrevious">False when the checks or the audit settings changed since the previous run, so a diff may reflect that change</param>
        /// <param name="newIssues">newIssues</param>
        /// <param name="fixedIssues">fixedIssues</param>
        /// <param name="regressedIssues">regressedIssues</param>
        /// <param name="error">error</param>
        /// <param name="engineVersion">engineVersion</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="finishedAt">finishedAt</param>
        /// <param name="appUrl">appUrl</param>
        /// <param name="projectId">projectId</param>
        /// <param name="requestId">requestId</param>
        [JsonConstructor]
        public GeoAuditRunResponse(Option<int?> sequence = default, Option<StatusEnum?> status = default, Option<TriggerEnum?> trigger = default, Option<decimal?> score = default, Option<string?> grade = default, Option<decimal?> scoreDelta = default, Option<bool?> comparableToPrevious = default, Option<int?> newIssues = default, Option<int?> fixedIssues = default, Option<int?> regressedIssues = default, Option<string?> error = default, Option<string?> engineVersion = default, Option<DateTime?> createdAt = default, Option<DateTime?> finishedAt = default, Option<string?> appUrl = default, Option<int?> projectId = default, Option<string?> requestId = default)
        {
            SequenceOption = sequence;
            StatusOption = status;
            TriggerOption = trigger;
            ScoreOption = score;
            GradeOption = grade;
            ScoreDeltaOption = scoreDelta;
            ComparableToPreviousOption = comparableToPrevious;
            NewIssuesOption = newIssues;
            FixedIssuesOption = fixedIssues;
            RegressedIssuesOption = regressedIssues;
            ErrorOption = error;
            EngineVersionOption = engineVersion;
            CreatedAtOption = createdAt;
            FinishedAtOption = finishedAt;
            AppUrlOption = appUrl;
            ProjectIdOption = projectId;
            RequestIdOption = requestId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Queued for value: queued
            /// </summary>
            Queued = 1,

            /// <summary>
            /// Enum Running for value: running
            /// </summary>
            Running = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            Completed = 3,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 4,

            /// <summary>
            /// Enum Unreachable for value: unreachable
            /// </summary>
            Unreachable = 5
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("queued"))
                return StatusEnum.Queued;

            if (value.Equals("running"))
                return StatusEnum.Running;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            if (value.Equals("unreachable"))
                return StatusEnum.Unreachable;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("queued"))
                return StatusEnum.Queued;

            if (value.Equals("running"))
                return StatusEnum.Running;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            if (value.Equals("unreachable"))
                return StatusEnum.Unreachable;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Queued)
                return "queued";

            if (value == StatusEnum.Running)
                return "running";

            if (value == StatusEnum.Completed)
                return "completed";

            if (value == StatusEnum.Failed)
                return "failed";

            if (value == StatusEnum.Unreachable)
                return "unreachable";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Defines Trigger
        /// </summary>
        public enum TriggerEnum
        {
            /// <summary>
            /// Enum Scheduled for value: scheduled
            /// </summary>
            Scheduled = 1,

            /// <summary>
            /// Enum Manual for value: manual
            /// </summary>
            Manual = 2,

            /// <summary>
            /// Enum Api for value: api
            /// </summary>
            Api = 3,

            /// <summary>
            /// Enum Mcp for value: mcp
            /// </summary>
            Mcp = 4,

            /// <summary>
            /// Enum LegacyImport for value: legacy_import
            /// </summary>
            LegacyImport = 5
        }

        /// <summary>
        /// Returns a <see cref="TriggerEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TriggerEnum TriggerEnumFromString(string value)
        {
            if (value.Equals("scheduled"))
                return TriggerEnum.Scheduled;

            if (value.Equals("manual"))
                return TriggerEnum.Manual;

            if (value.Equals("api"))
                return TriggerEnum.Api;

            if (value.Equals("mcp"))
                return TriggerEnum.Mcp;

            if (value.Equals("legacy_import"))
                return TriggerEnum.LegacyImport;

            throw new NotImplementedException($"Could not convert value to type TriggerEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TriggerEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TriggerEnum? TriggerEnumFromStringOrDefault(string value)
        {
            if (value.Equals("scheduled"))
                return TriggerEnum.Scheduled;

            if (value.Equals("manual"))
                return TriggerEnum.Manual;

            if (value.Equals("api"))
                return TriggerEnum.Api;

            if (value.Equals("mcp"))
                return TriggerEnum.Mcp;

            if (value.Equals("legacy_import"))
                return TriggerEnum.LegacyImport;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TriggerEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TriggerEnumToJsonValue(TriggerEnum? value)
        {
            if (value == TriggerEnum.Scheduled)
                return "scheduled";

            if (value == TriggerEnum.Manual)
                return "manual";

            if (value == TriggerEnum.Api)
                return "api";

            if (value == TriggerEnum.Mcp)
                return "mcp";

            if (value == TriggerEnum.LegacyImport)
                return "legacy_import";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Trigger
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TriggerEnum?> TriggerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Trigger
        /// </summary>
        [JsonPropertyName("trigger")]
        public TriggerEnum? Trigger { get { return this.TriggerOption.Value; } set { this.TriggerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sequence
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SequenceOption { get; private set; }

        /// <summary>
        /// Run number within the audit, starting at 1
        /// </summary>
        /// <value>Run number within the audit, starting at 1</value>
        [JsonPropertyName("sequence")]
        public int? Sequence { get { return this.SequenceOption.Value; } set { this.SequenceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Score
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>
        [JsonPropertyName("score")]
        public decimal? Score { get { return this.ScoreOption.Value; } set { this.ScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of Grade
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GradeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Grade
        /// </summary>
        [JsonPropertyName("grade")]
        public string? Grade { get { return this.GradeOption.Value; } set { this.GradeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ScoreDelta
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ScoreDeltaOption { get; private set; }

        /// <summary>
        /// Score change against the previous completed run
        /// </summary>
        /// <value>Score change against the previous completed run</value>
        [JsonPropertyName("score_delta")]
        public decimal? ScoreDelta { get { return this.ScoreDeltaOption.Value; } set { this.ScoreDeltaOption = new(value); } }

        /// <summary>
        /// Used to track the state of ComparableToPrevious
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ComparableToPreviousOption { get; private set; }

        /// <summary>
        /// False when the checks or the audit settings changed since the previous run, so a diff may reflect that change
        /// </summary>
        /// <value>False when the checks or the audit settings changed since the previous run, so a diff may reflect that change</value>
        [JsonPropertyName("comparable_to_previous")]
        public bool? ComparableToPrevious { get { return this.ComparableToPreviousOption.Value; } set { this.ComparableToPreviousOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewIssues
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NewIssuesOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewIssues
        /// </summary>
        [JsonPropertyName("new_issues")]
        public int? NewIssues { get { return this.NewIssuesOption.Value; } set { this.NewIssuesOption = new(value); } }

        /// <summary>
        /// Used to track the state of FixedIssues
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FixedIssuesOption { get; private set; }

        /// <summary>
        /// Gets or Sets FixedIssues
        /// </summary>
        [JsonPropertyName("fixed_issues")]
        public int? FixedIssues { get { return this.FixedIssuesOption.Value; } set { this.FixedIssuesOption = new(value); } }

        /// <summary>
        /// Used to track the state of RegressedIssues
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RegressedIssuesOption { get; private set; }

        /// <summary>
        /// Gets or Sets RegressedIssues
        /// </summary>
        [JsonPropertyName("regressed_issues")]
        public int? RegressedIssues { get { return this.RegressedIssuesOption.Value; } set { this.RegressedIssuesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public string? Error { get { return this.ErrorOption.Value; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Used to track the state of EngineVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EngineVersionOption { get; private set; }

        /// <summary>
        /// Gets or Sets EngineVersion
        /// </summary>
        [JsonPropertyName("engine_version")]
        public string? EngineVersion { get { return this.EngineVersionOption.Value; } set { this.EngineVersionOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of FinishedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> FinishedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets FinishedAt
        /// </summary>
        [JsonPropertyName("finished_at")]
        public DateTime? FinishedAt { get { return this.FinishedAtOption.Value; } set { this.FinishedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of AppUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AppUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets AppUrl
        /// </summary>
        [JsonPropertyName("app_url")]
        public string? AppUrl { get { return this.AppUrlOption.Value; } set { this.AppUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProjectId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ProjectIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("project_id")]
        public int? ProjectId { get { return this.ProjectIdOption.Value; } set { this.ProjectIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequestId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RequestIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>
        [JsonPropertyName("request_id")]
        public string? RequestId { get { return this.RequestIdOption.Value; } set { this.RequestIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeoAuditRunResponse {\n");
            sb.Append("  Sequence: ").Append(Sequence).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Trigger: ").Append(Trigger).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  Grade: ").Append(Grade).Append("\n");
            sb.Append("  ScoreDelta: ").Append(ScoreDelta).Append("\n");
            sb.Append("  ComparableToPrevious: ").Append(ComparableToPrevious).Append("\n");
            sb.Append("  NewIssues: ").Append(NewIssues).Append("\n");
            sb.Append("  FixedIssues: ").Append(FixedIssues).Append("\n");
            sb.Append("  RegressedIssues: ").Append(RegressedIssues).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  EngineVersion: ").Append(EngineVersion).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  FinishedAt: ").Append(FinishedAt).Append("\n");
            sb.Append("  AppUrl: ").Append(AppUrl).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GeoAuditRunResponse" />
    /// </summary>
    public partial class GeoAuditRunResponseJsonConverter : JsonConverter<GeoAuditRunResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GeoAuditRunResponseJsonConverter" /> class.
        /// </summary>
        public GeoAuditRunResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize FinishedAt
        /// </summary>
        public string FinishedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="GeoAuditRunResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GeoAuditRunResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> sequence = default;
            Option<GeoAuditRunResponse.StatusEnum?> status = default;
            Option<GeoAuditRunResponse.TriggerEnum?> trigger = default;
            Option<decimal?> score = default;
            Option<string?> grade = default;
            Option<decimal?> scoreDelta = default;
            Option<bool?> comparableToPrevious = default;
            Option<int?> newIssues = default;
            Option<int?> fixedIssues = default;
            Option<int?> regressedIssues = default;
            Option<string?> error = default;
            Option<string?> engineVersion = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> finishedAt = default;
            Option<string?> appUrl = default;
            Option<int?> projectId = default;
            Option<string?> requestId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sequence":
                            sequence = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<GeoAuditRunResponse.StatusEnum?>(GeoAuditRunResponse.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "trigger":
                            string? triggerRawValue = utf8JsonReader.GetString();
                            if (triggerRawValue != null)
                                trigger = new Option<GeoAuditRunResponse.TriggerEnum?>(GeoAuditRunResponse.TriggerEnumFromStringOrDefault(triggerRawValue));
                            break;
                        case "score":
                            score = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "grade":
                            grade = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "score_delta":
                            scoreDelta = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "comparable_to_previous":
                            comparableToPrevious = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "new_issues":
                            newIssues = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "fixed_issues":
                            fixedIssues = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "regressed_issues":
                            regressedIssues = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "engine_version":
                            engineVersion = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "finished_at":
                            finishedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "app_url":
                            appUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "project_id":
                            projectId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "request_id":
                            requestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (sequence.IsSet && sequence.Value == null)
                throw new ArgumentNullException(nameof(sequence), "Property is not nullable for class GeoAuditRunResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class GeoAuditRunResponse.");

            if (trigger.IsSet && trigger.Value == null)
                throw new ArgumentNullException(nameof(trigger), "Property is not nullable for class GeoAuditRunResponse.");

            if (comparableToPrevious.IsSet && comparableToPrevious.Value == null)
                throw new ArgumentNullException(nameof(comparableToPrevious), "Property is not nullable for class GeoAuditRunResponse.");

            if (newIssues.IsSet && newIssues.Value == null)
                throw new ArgumentNullException(nameof(newIssues), "Property is not nullable for class GeoAuditRunResponse.");

            if (fixedIssues.IsSet && fixedIssues.Value == null)
                throw new ArgumentNullException(nameof(fixedIssues), "Property is not nullable for class GeoAuditRunResponse.");

            if (regressedIssues.IsSet && regressedIssues.Value == null)
                throw new ArgumentNullException(nameof(regressedIssues), "Property is not nullable for class GeoAuditRunResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class GeoAuditRunResponse.");

            if (appUrl.IsSet && appUrl.Value == null)
                throw new ArgumentNullException(nameof(appUrl), "Property is not nullable for class GeoAuditRunResponse.");

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class GeoAuditRunResponse.");

            if (requestId.IsSet && requestId.Value == null)
                throw new ArgumentNullException(nameof(requestId), "Property is not nullable for class GeoAuditRunResponse.");

            return new GeoAuditRunResponse(sequence, status, trigger, score, grade, scoreDelta, comparableToPrevious, newIssues, fixedIssues, regressedIssues, error, engineVersion, createdAt, finishedAt, appUrl, projectId, requestId);
        }

        /// <summary>
        /// Serializes a <see cref="GeoAuditRunResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geoAuditRunResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GeoAuditRunResponse geoAuditRunResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, geoAuditRunResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GeoAuditRunResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geoAuditRunResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GeoAuditRunResponse geoAuditRunResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (geoAuditRunResponse.AppUrlOption.IsSet && geoAuditRunResponse.AppUrl == null)
                throw new ArgumentNullException(nameof(geoAuditRunResponse.AppUrl), "Property is required for class GeoAuditRunResponse.");

            if (geoAuditRunResponse.RequestIdOption.IsSet && geoAuditRunResponse.RequestId == null)
                throw new ArgumentNullException(nameof(geoAuditRunResponse.RequestId), "Property is required for class GeoAuditRunResponse.");

            if (geoAuditRunResponse.SequenceOption.IsSet)
                writer.WriteNumber("sequence", geoAuditRunResponse.SequenceOption.Value!.Value);

            var statusRawValue = GeoAuditRunResponse.StatusEnumToJsonValue(geoAuditRunResponse.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            var triggerRawValue = GeoAuditRunResponse.TriggerEnumToJsonValue(geoAuditRunResponse.TriggerOption.Value!.Value);
            writer.WriteString("trigger", triggerRawValue);
            if (geoAuditRunResponse.ScoreOption.IsSet)
                if (geoAuditRunResponse.ScoreOption.Value != null)
                    writer.WriteNumber("score", geoAuditRunResponse.ScoreOption.Value!.Value);
                else
                    writer.WriteNull("score");

            if (geoAuditRunResponse.GradeOption.IsSet)
                if (geoAuditRunResponse.GradeOption.Value != null)
                    writer.WriteString("grade", geoAuditRunResponse.Grade);
                else
                    writer.WriteNull("grade");

            if (geoAuditRunResponse.ScoreDeltaOption.IsSet)
                if (geoAuditRunResponse.ScoreDeltaOption.Value != null)
                    writer.WriteNumber("score_delta", geoAuditRunResponse.ScoreDeltaOption.Value!.Value);
                else
                    writer.WriteNull("score_delta");

            if (geoAuditRunResponse.ComparableToPreviousOption.IsSet)
                writer.WriteBoolean("comparable_to_previous", geoAuditRunResponse.ComparableToPreviousOption.Value!.Value);

            if (geoAuditRunResponse.NewIssuesOption.IsSet)
                writer.WriteNumber("new_issues", geoAuditRunResponse.NewIssuesOption.Value!.Value);

            if (geoAuditRunResponse.FixedIssuesOption.IsSet)
                writer.WriteNumber("fixed_issues", geoAuditRunResponse.FixedIssuesOption.Value!.Value);

            if (geoAuditRunResponse.RegressedIssuesOption.IsSet)
                writer.WriteNumber("regressed_issues", geoAuditRunResponse.RegressedIssuesOption.Value!.Value);

            if (geoAuditRunResponse.ErrorOption.IsSet)
                if (geoAuditRunResponse.ErrorOption.Value != null)
                    writer.WriteString("error", geoAuditRunResponse.Error);
                else
                    writer.WriteNull("error");

            if (geoAuditRunResponse.EngineVersionOption.IsSet)
                if (geoAuditRunResponse.EngineVersionOption.Value != null)
                    writer.WriteString("engine_version", geoAuditRunResponse.EngineVersion);
                else
                    writer.WriteNull("engine_version");

            if (geoAuditRunResponse.CreatedAtOption.IsSet)
                writer.WriteString("created_at", geoAuditRunResponse.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (geoAuditRunResponse.FinishedAtOption.IsSet)
                if (geoAuditRunResponse.FinishedAtOption.Value != null)
                    writer.WriteString("finished_at", geoAuditRunResponse.FinishedAtOption.Value!.Value.ToString(FinishedAtFormat));
                else
                    writer.WriteNull("finished_at");

            if (geoAuditRunResponse.AppUrlOption.IsSet)
                writer.WriteString("app_url", geoAuditRunResponse.AppUrl);

            if (geoAuditRunResponse.ProjectIdOption.IsSet)
                writer.WriteNumber("project_id", geoAuditRunResponse.ProjectIdOption.Value!.Value);

            if (geoAuditRunResponse.RequestIdOption.IsSet)
                writer.WriteString("request_id", geoAuditRunResponse.RequestId);
        }
    }
}
