// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.53.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// The files and generation details once the report has completed; null before that
    /// </summary>
    public partial class LlmsTxtTechnicalGeoReportResultData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LlmsTxtTechnicalGeoReportResultData" /> class.
        /// </summary>
        /// <param name="llmsTxtContent">Current llms.txt, manual edits included</param>
        /// <param name="llmsFullTxtContent">Current llms-full.txt, manual edits included</param>
        /// <param name="manuallyEditedAt">When the files were last edited by hand in the app, the API or MCP; null while they are as generated</param>
        /// <param name="contentVersion">Send it back as content_version when editing the files. It changes on every save</param>
        /// <param name="originalLlmsTxtContent">The generated llms.txt, kept from the first manual edit; null while the files are as generated</param>
        /// <param name="originalLlmsFullTxtContent">The generated llms-full.txt, kept from the first manual edit; null while the files are as generated</param>
        /// <param name="crawlData">crawlData</param>
        /// <param name="metadata">Generation details, including output_language_code, the language the files were written in</param>
        /// <param name="pagesCrawled">pagesCrawled</param>
        /// <param name="generationTimeMs">generationTimeMs</param>
        /// <param name="openaiTokensUsed">openaiTokensUsed</param>
        [JsonConstructor]
        public LlmsTxtTechnicalGeoReportResultData(Option<string?> llmsTxtContent = default, Option<string?> llmsFullTxtContent = default, Option<DateTime?> manuallyEditedAt = default, Option<string?> contentVersion = default, Option<string?> originalLlmsTxtContent = default, Option<string?> originalLlmsFullTxtContent = default, Option<Object?> crawlData = default, Option<Object?> metadata = default, Option<int?> pagesCrawled = default, Option<int?> generationTimeMs = default, Option<int?> openaiTokensUsed = default)
        {
            LlmsTxtContentOption = llmsTxtContent;
            LlmsFullTxtContentOption = llmsFullTxtContent;
            ManuallyEditedAtOption = manuallyEditedAt;
            ContentVersionOption = contentVersion;
            OriginalLlmsTxtContentOption = originalLlmsTxtContent;
            OriginalLlmsFullTxtContentOption = originalLlmsFullTxtContent;
            CrawlDataOption = crawlData;
            MetadataOption = metadata;
            PagesCrawledOption = pagesCrawled;
            GenerationTimeMsOption = generationTimeMs;
            OpenaiTokensUsedOption = openaiTokensUsed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LlmsTxtContent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LlmsTxtContentOption { get; private set; }

        /// <summary>
        /// Current llms.txt, manual edits included
        /// </summary>
        /// <value>Current llms.txt, manual edits included</value>
        [JsonPropertyName("llms_txt_content")]
        public string? LlmsTxtContent { get { return this.LlmsTxtContentOption.Value; } set { this.LlmsTxtContentOption = new(value); } }

        /// <summary>
        /// Used to track the state of LlmsFullTxtContent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LlmsFullTxtContentOption { get; private set; }

        /// <summary>
        /// Current llms-full.txt, manual edits included
        /// </summary>
        /// <value>Current llms-full.txt, manual edits included</value>
        [JsonPropertyName("llms_full_txt_content")]
        public string? LlmsFullTxtContent { get { return this.LlmsFullTxtContentOption.Value; } set { this.LlmsFullTxtContentOption = new(value); } }

        /// <summary>
        /// Used to track the state of ManuallyEditedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ManuallyEditedAtOption { get; private set; }

        /// <summary>
        /// When the files were last edited by hand in the app, the API or MCP; null while they are as generated
        /// </summary>
        /// <value>When the files were last edited by hand in the app, the API or MCP; null while they are as generated</value>
        [JsonPropertyName("manually_edited_at")]
        public DateTime? ManuallyEditedAt { get { return this.ManuallyEditedAtOption.Value; } set { this.ManuallyEditedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContentVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContentVersionOption { get; private set; }

        /// <summary>
        /// Send it back as content_version when editing the files. It changes on every save
        /// </summary>
        /// <value>Send it back as content_version when editing the files. It changes on every save</value>
        [JsonPropertyName("content_version")]
        public string? ContentVersion { get { return this.ContentVersionOption.Value; } set { this.ContentVersionOption = new(value); } }

        /// <summary>
        /// Used to track the state of OriginalLlmsTxtContent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OriginalLlmsTxtContentOption { get; private set; }

        /// <summary>
        /// The generated llms.txt, kept from the first manual edit; null while the files are as generated
        /// </summary>
        /// <value>The generated llms.txt, kept from the first manual edit; null while the files are as generated</value>
        [JsonPropertyName("original_llms_txt_content")]
        public string? OriginalLlmsTxtContent { get { return this.OriginalLlmsTxtContentOption.Value; } set { this.OriginalLlmsTxtContentOption = new(value); } }

        /// <summary>
        /// Used to track the state of OriginalLlmsFullTxtContent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OriginalLlmsFullTxtContentOption { get; private set; }

        /// <summary>
        /// The generated llms-full.txt, kept from the first manual edit; null while the files are as generated
        /// </summary>
        /// <value>The generated llms-full.txt, kept from the first manual edit; null while the files are as generated</value>
        [JsonPropertyName("original_llms_full_txt_content")]
        public string? OriginalLlmsFullTxtContent { get { return this.OriginalLlmsFullTxtContentOption.Value; } set { this.OriginalLlmsFullTxtContentOption = new(value); } }

        /// <summary>
        /// Used to track the state of CrawlData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> CrawlDataOption { get; private set; }

        /// <summary>
        /// Gets or Sets CrawlData
        /// </summary>
        [JsonPropertyName("crawl_data")]
        public Object? CrawlData { get { return this.CrawlDataOption.Value; } set { this.CrawlDataOption = new(value); } }

        /// <summary>
        /// Used to track the state of Metadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> MetadataOption { get; private set; }

        /// <summary>
        /// Generation details, including output_language_code, the language the files were written in
        /// </summary>
        /// <value>Generation details, including output_language_code, the language the files were written in</value>
        [JsonPropertyName("metadata")]
        public Object? Metadata { get { return this.MetadataOption.Value; } set { this.MetadataOption = new(value); } }

        /// <summary>
        /// Used to track the state of PagesCrawled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PagesCrawledOption { get; private set; }

        /// <summary>
        /// Gets or Sets PagesCrawled
        /// </summary>
        [JsonPropertyName("pages_crawled")]
        public int? PagesCrawled { get { return this.PagesCrawledOption.Value; } set { this.PagesCrawledOption = new(value); } }

        /// <summary>
        /// Used to track the state of GenerationTimeMs
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> GenerationTimeMsOption { get; private set; }

        /// <summary>
        /// Gets or Sets GenerationTimeMs
        /// </summary>
        [JsonPropertyName("generation_time_ms")]
        public int? GenerationTimeMs { get { return this.GenerationTimeMsOption.Value; } set { this.GenerationTimeMsOption = new(value); } }

        /// <summary>
        /// Used to track the state of OpenaiTokensUsed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OpenaiTokensUsedOption { get; private set; }

        /// <summary>
        /// Gets or Sets OpenaiTokensUsed
        /// </summary>
        [JsonPropertyName("openai_tokens_used")]
        public int? OpenaiTokensUsed { get { return this.OpenaiTokensUsedOption.Value; } set { this.OpenaiTokensUsedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LlmsTxtTechnicalGeoReportResultData {\n");
            sb.Append("  LlmsTxtContent: ").Append(LlmsTxtContent).Append("\n");
            sb.Append("  LlmsFullTxtContent: ").Append(LlmsFullTxtContent).Append("\n");
            sb.Append("  ManuallyEditedAt: ").Append(ManuallyEditedAt).Append("\n");
            sb.Append("  ContentVersion: ").Append(ContentVersion).Append("\n");
            sb.Append("  OriginalLlmsTxtContent: ").Append(OriginalLlmsTxtContent).Append("\n");
            sb.Append("  OriginalLlmsFullTxtContent: ").Append(OriginalLlmsFullTxtContent).Append("\n");
            sb.Append("  CrawlData: ").Append(CrawlData).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  PagesCrawled: ").Append(PagesCrawled).Append("\n");
            sb.Append("  GenerationTimeMs: ").Append(GenerationTimeMs).Append("\n");
            sb.Append("  OpenaiTokensUsed: ").Append(OpenaiTokensUsed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LlmsTxtTechnicalGeoReportResultData" />
    /// </summary>
    public partial class LlmsTxtTechnicalGeoReportResultDataJsonConverter : JsonConverter<LlmsTxtTechnicalGeoReportResultData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="LlmsTxtTechnicalGeoReportResultDataJsonConverter" /> class.
        /// </summary>
        public LlmsTxtTechnicalGeoReportResultDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ManuallyEditedAt
        /// </summary>
        public string ManuallyEditedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="LlmsTxtTechnicalGeoReportResultData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LlmsTxtTechnicalGeoReportResultData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> llmsTxtContent = default;
            Option<string?> llmsFullTxtContent = default;
            Option<DateTime?> manuallyEditedAt = default;
            Option<string?> contentVersion = default;
            Option<string?> originalLlmsTxtContent = default;
            Option<string?> originalLlmsFullTxtContent = default;
            Option<Object?> crawlData = default;
            Option<Object?> metadata = default;
            Option<int?> pagesCrawled = default;
            Option<int?> generationTimeMs = default;
            Option<int?> openaiTokensUsed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "llms_txt_content":
                            llmsTxtContent = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "llms_full_txt_content":
                            llmsFullTxtContent = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "manually_edited_at":
                            manuallyEditedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "content_version":
                            contentVersion = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "original_llms_txt_content":
                            originalLlmsTxtContent = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "original_llms_full_txt_content":
                            originalLlmsFullTxtContent = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "crawl_data":
                            crawlData = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "metadata":
                            metadata = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "pages_crawled":
                            pagesCrawled = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "generation_time_ms":
                            generationTimeMs = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "openai_tokens_used":
                            openaiTokensUsed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (llmsTxtContent.IsSet && llmsTxtContent.Value == null)
                throw new ArgumentNullException(nameof(llmsTxtContent), "Property is not nullable for class LlmsTxtTechnicalGeoReportResultData.");

            if (contentVersion.IsSet && contentVersion.Value == null)
                throw new ArgumentNullException(nameof(contentVersion), "Property is not nullable for class LlmsTxtTechnicalGeoReportResultData.");

            return new LlmsTxtTechnicalGeoReportResultData(llmsTxtContent, llmsFullTxtContent, manuallyEditedAt, contentVersion, originalLlmsTxtContent, originalLlmsFullTxtContent, crawlData, metadata, pagesCrawled, generationTimeMs, openaiTokensUsed);
        }

        /// <summary>
        /// Serializes a <see cref="LlmsTxtTechnicalGeoReportResultData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="llmsTxtTechnicalGeoReportResultData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LlmsTxtTechnicalGeoReportResultData llmsTxtTechnicalGeoReportResultData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, llmsTxtTechnicalGeoReportResultData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LlmsTxtTechnicalGeoReportResultData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="llmsTxtTechnicalGeoReportResultData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LlmsTxtTechnicalGeoReportResultData llmsTxtTechnicalGeoReportResultData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (llmsTxtTechnicalGeoReportResultData.LlmsTxtContentOption.IsSet && llmsTxtTechnicalGeoReportResultData.LlmsTxtContent == null)
                throw new ArgumentNullException(nameof(llmsTxtTechnicalGeoReportResultData.LlmsTxtContent), "Property is required for class LlmsTxtTechnicalGeoReportResultData.");

            if (llmsTxtTechnicalGeoReportResultData.ContentVersionOption.IsSet && llmsTxtTechnicalGeoReportResultData.ContentVersion == null)
                throw new ArgumentNullException(nameof(llmsTxtTechnicalGeoReportResultData.ContentVersion), "Property is required for class LlmsTxtTechnicalGeoReportResultData.");

            if (llmsTxtTechnicalGeoReportResultData.LlmsTxtContentOption.IsSet)
                writer.WriteString("llms_txt_content", llmsTxtTechnicalGeoReportResultData.LlmsTxtContent);

            if (llmsTxtTechnicalGeoReportResultData.LlmsFullTxtContentOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.LlmsFullTxtContentOption.Value != null)
                    writer.WriteString("llms_full_txt_content", llmsTxtTechnicalGeoReportResultData.LlmsFullTxtContent);
                else
                    writer.WriteNull("llms_full_txt_content");

            if (llmsTxtTechnicalGeoReportResultData.ManuallyEditedAtOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.ManuallyEditedAtOption.Value != null)
                    writer.WriteString("manually_edited_at", llmsTxtTechnicalGeoReportResultData.ManuallyEditedAtOption.Value!.Value.ToString(ManuallyEditedAtFormat));
                else
                    writer.WriteNull("manually_edited_at");

            if (llmsTxtTechnicalGeoReportResultData.ContentVersionOption.IsSet)
                writer.WriteString("content_version", llmsTxtTechnicalGeoReportResultData.ContentVersion);

            if (llmsTxtTechnicalGeoReportResultData.OriginalLlmsTxtContentOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.OriginalLlmsTxtContentOption.Value != null)
                    writer.WriteString("original_llms_txt_content", llmsTxtTechnicalGeoReportResultData.OriginalLlmsTxtContent);
                else
                    writer.WriteNull("original_llms_txt_content");

            if (llmsTxtTechnicalGeoReportResultData.OriginalLlmsFullTxtContentOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.OriginalLlmsFullTxtContentOption.Value != null)
                    writer.WriteString("original_llms_full_txt_content", llmsTxtTechnicalGeoReportResultData.OriginalLlmsFullTxtContent);
                else
                    writer.WriteNull("original_llms_full_txt_content");

            if (llmsTxtTechnicalGeoReportResultData.CrawlDataOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.CrawlDataOption.Value != null)
                {
                    writer.WritePropertyName("crawl_data");
                    JsonSerializer.Serialize(writer, llmsTxtTechnicalGeoReportResultData.CrawlData, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("crawl_data");
            if (llmsTxtTechnicalGeoReportResultData.MetadataOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.MetadataOption.Value != null)
                {
                    writer.WritePropertyName("metadata");
                    JsonSerializer.Serialize(writer, llmsTxtTechnicalGeoReportResultData.Metadata, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("metadata");
            if (llmsTxtTechnicalGeoReportResultData.PagesCrawledOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.PagesCrawledOption.Value != null)
                    writer.WriteNumber("pages_crawled", llmsTxtTechnicalGeoReportResultData.PagesCrawledOption.Value!.Value);
                else
                    writer.WriteNull("pages_crawled");

            if (llmsTxtTechnicalGeoReportResultData.GenerationTimeMsOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.GenerationTimeMsOption.Value != null)
                    writer.WriteNumber("generation_time_ms", llmsTxtTechnicalGeoReportResultData.GenerationTimeMsOption.Value!.Value);
                else
                    writer.WriteNull("generation_time_ms");

            if (llmsTxtTechnicalGeoReportResultData.OpenaiTokensUsedOption.IsSet)
                if (llmsTxtTechnicalGeoReportResultData.OpenaiTokensUsedOption.Value != null)
                    writer.WriteNumber("openai_tokens_used", llmsTxtTechnicalGeoReportResultData.OpenaiTokensUsedOption.Value!.Value);
                else
                    writer.WriteNull("openai_tokens_used");
        }
    }
}
