// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// LocalesResponse
    /// </summary>
    public partial class LocalesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalesResponse" /> class.
        /// </summary>
        /// <param name="projectId">projectId</param>
        /// <param name="countries">Country codes with data</param>
        /// <param name="languages">Language codes with data</param>
        /// <param name="requestId">requestId</param>
        [JsonConstructor]
        public LocalesResponse(int projectId, List<string> countries, List<string> languages, string requestId)
        {
            ProjectId = projectId;
            Countries = countries;
            Languages = languages;
            RequestId = requestId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("project_id")]
        public int ProjectId { get; set; }

        /// <summary>
        /// Country codes with data
        /// </summary>
        /// <value>Country codes with data</value>
        [JsonPropertyName("countries")]
        public List<string> Countries { get; set; }

        /// <summary>
        /// Language codes with data
        /// </summary>
        /// <value>Language codes with data</value>
        [JsonPropertyName("languages")]
        public List<string> Languages { get; set; }

        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>
        [JsonPropertyName("request_id")]
        public string RequestId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LocalesResponse {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Countries: ").Append(Countries).Append("\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LocalesResponse" />
    /// </summary>
    public partial class LocalesResponseJsonConverter : JsonConverter<LocalesResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalesResponseJsonConverter" /> class.
        /// </summary>
        public LocalesResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="LocalesResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LocalesResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> projectId = default;
            Option<List<string>?> countries = default;
            Option<List<string>?> languages = default;
            Option<string?> requestId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "project_id":
                            projectId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "countries":
                            countries = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "languages":
                            languages = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "request_id":
                            requestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!projectId.IsSet)
                throw new ArgumentException("Property is required for class LocalesResponse.", nameof(projectId));

            if (!countries.IsSet)
                throw new ArgumentException("Property is required for class LocalesResponse.", nameof(countries));

            if (!languages.IsSet)
                throw new ArgumentException("Property is required for class LocalesResponse.", nameof(languages));

            if (!requestId.IsSet)
                throw new ArgumentException("Property is required for class LocalesResponse.", nameof(requestId));

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class LocalesResponse.");

            if (countries.IsSet && countries.Value == null)
                throw new ArgumentNullException(nameof(countries), "Property is not nullable for class LocalesResponse.");

            if (languages.IsSet && languages.Value == null)
                throw new ArgumentNullException(nameof(languages), "Property is not nullable for class LocalesResponse.");

            if (requestId.IsSet && requestId.Value == null)
                throw new ArgumentNullException(nameof(requestId), "Property is not nullable for class LocalesResponse.");

            return new LocalesResponse(projectId.Value!.Value!, countries.Value!, languages.Value!, requestId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="LocalesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="localesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LocalesResponse localesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, localesResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LocalesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="localesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LocalesResponse localesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (localesResponse.Countries == null)
                throw new ArgumentNullException(nameof(localesResponse.Countries), "Property is required for class LocalesResponse.");

            if (localesResponse.Languages == null)
                throw new ArgumentNullException(nameof(localesResponse.Languages), "Property is required for class LocalesResponse.");

            if (localesResponse.RequestId == null)
                throw new ArgumentNullException(nameof(localesResponse.RequestId), "Property is required for class LocalesResponse.");

            writer.WriteNumber("project_id", localesResponse.ProjectId);

            writer.WritePropertyName("countries");
            JsonSerializer.Serialize(writer, localesResponse.Countries, jsonSerializerOptions);
            writer.WritePropertyName("languages");
            JsonSerializer.Serialize(writer, localesResponse.Languages, jsonSerializerOptions);
            writer.WriteString("request_id", localesResponse.RequestId);
        }
    }
}
