// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// ProjectCreateResponseEmailSubscription
    /// </summary>
    public partial class ProjectCreateResponseEmailSubscription : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectCreateResponseEmailSubscription" /> class.
        /// </summary>
        /// <param name="weeklyEmailSubscribed">weeklyEmailSubscribed</param>
        [JsonConstructor]
        public ProjectCreateResponseEmailSubscription(Option<bool?> weeklyEmailSubscribed = default)
        {
            WeeklyEmailSubscribedOption = weeklyEmailSubscribed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of WeeklyEmailSubscribed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> WeeklyEmailSubscribedOption { get; private set; }

        /// <summary>
        /// Gets or Sets WeeklyEmailSubscribed
        /// </summary>
        [JsonPropertyName("weekly_email_subscribed")]
        public bool? WeeklyEmailSubscribed { get { return this.WeeklyEmailSubscribedOption.Value; } set { this.WeeklyEmailSubscribedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectCreateResponseEmailSubscription {\n");
            sb.Append("  WeeklyEmailSubscribed: ").Append(WeeklyEmailSubscribed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProjectCreateResponseEmailSubscription" />
    /// </summary>
    public partial class ProjectCreateResponseEmailSubscriptionJsonConverter : JsonConverter<ProjectCreateResponseEmailSubscription>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectCreateResponseEmailSubscriptionJsonConverter" /> class.
        /// </summary>
        public ProjectCreateResponseEmailSubscriptionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ProjectCreateResponseEmailSubscription" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProjectCreateResponseEmailSubscription Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> weeklyEmailSubscribed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "weekly_email_subscribed":
                            weeklyEmailSubscribed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (weeklyEmailSubscribed.IsSet && weeklyEmailSubscribed.Value == null)
                throw new ArgumentNullException(nameof(weeklyEmailSubscribed), "Property is not nullable for class ProjectCreateResponseEmailSubscription.");

            return new ProjectCreateResponseEmailSubscription(weeklyEmailSubscribed);
        }

        /// <summary>
        /// Serializes a <see cref="ProjectCreateResponseEmailSubscription" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="projectCreateResponseEmailSubscription"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProjectCreateResponseEmailSubscription projectCreateResponseEmailSubscription, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, projectCreateResponseEmailSubscription, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProjectCreateResponseEmailSubscription" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="projectCreateResponseEmailSubscription"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProjectCreateResponseEmailSubscription projectCreateResponseEmailSubscription, JsonSerializerOptions jsonSerializerOptions)
        {
            if (projectCreateResponseEmailSubscription.WeeklyEmailSubscribedOption.IsSet)
                writer.WriteBoolean("weekly_email_subscribed", projectCreateResponseEmailSubscription.WeeklyEmailSubscribedOption.Value!.Value);
        }
    }
}
