// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// QueryWebAnalyticsRequest
    /// </summary>
    public partial class QueryWebAnalyticsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryWebAnalyticsRequest" /> class.
        /// </summary>
        /// <param name="projectId">projectId</param>
        /// <param name="query">The query in the provider&#39;s native format (see GET /web_analytics/schema): a JSON object for GA4, Adobe, Matomo, Plausible and Piano; for PostHog, {\&quot;query\&quot;: \&quot;&lt;HogQL&gt;\&quot;} or the HogQL string. Deliberately untyped so generated clients accept either shape.</param>
        [JsonConstructor]
        public QueryWebAnalyticsRequest(int projectId, Object? query = default)
        {
            ProjectId = projectId;
            Query = query;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [JsonPropertyName("project_id")]
        public int ProjectId { get; set; }

        /// <summary>
        /// The query in the provider&#39;s native format (see GET /web_analytics/schema): a JSON object for GA4, Adobe, Matomo, Plausible and Piano; for PostHog, {\&quot;query\&quot;: \&quot;&lt;HogQL&gt;\&quot;} or the HogQL string. Deliberately untyped so generated clients accept either shape.
        /// </summary>
        /// <value>The query in the provider&#39;s native format (see GET /web_analytics/schema): a JSON object for GA4, Adobe, Matomo, Plausible and Piano; for PostHog, {\&quot;query\&quot;: \&quot;&lt;HogQL&gt;\&quot;} or the HogQL string. Deliberately untyped so generated clients accept either shape.</value>
        [JsonPropertyName("query")]
        public Object? Query { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryWebAnalyticsRequest {\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueryWebAnalyticsRequest" />
    /// </summary>
    public partial class QueryWebAnalyticsRequestJsonConverter : JsonConverter<QueryWebAnalyticsRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="QueryWebAnalyticsRequestJsonConverter" /> class.
        /// </summary>
        public QueryWebAnalyticsRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="QueryWebAnalyticsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueryWebAnalyticsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> projectId = default;
            Option<Object?> query = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "project_id":
                            projectId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "query":
                            query = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!projectId.IsSet)
                throw new ArgumentException("Property is required for class QueryWebAnalyticsRequest.", nameof(projectId));

            if (!query.IsSet)
                throw new ArgumentException("Property is required for class QueryWebAnalyticsRequest.", nameof(query));

            if (projectId.IsSet && projectId.Value == null)
                throw new ArgumentNullException(nameof(projectId), "Property is not nullable for class QueryWebAnalyticsRequest.");

            return new QueryWebAnalyticsRequest(projectId.Value!.Value!, query.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="QueryWebAnalyticsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryWebAnalyticsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QueryWebAnalyticsRequest queryWebAnalyticsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queryWebAnalyticsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueryWebAnalyticsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryWebAnalyticsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QueryWebAnalyticsRequest queryWebAnalyticsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("project_id", queryWebAnalyticsRequest.ProjectId);

            if (queryWebAnalyticsRequest.Query != null)
            {
                writer.WritePropertyName("query");
                JsonSerializer.Serialize(writer, queryWebAnalyticsRequest.Query, jsonSerializerOptions);
            }
            else
                writer.WriteNull("query");
        }
    }
}
