// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// The live project the store maps to: its domain equals the store&#39;s, or is a parent or subdomain of it. Null when no project matches
    /// </summary>
    public partial class StoreConnectionResponseProject : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StoreConnectionResponseProject" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="domain">domain</param>
        /// <param name="countryCode">countryCode</param>
        /// <param name="languageCode">languageCode</param>
        [JsonConstructor]
        public StoreConnectionResponseProject(int id, string name, string domain, Option<string?> countryCode = default, Option<string?> languageCode = default)
        {
            Id = id;
            Name = name;
            Domain = domain;
            CountryCodeOption = countryCode;
            LanguageCodeOption = languageCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Domain
        /// </summary>
        [JsonPropertyName("domain")]
        public string Domain { get; set; }

        /// <summary>
        /// Used to track the state of CountryCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        [JsonPropertyName("country_code")]
        public string? CountryCode { get { return this.CountryCodeOption.Value; } set { this.CountryCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of LanguageCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LanguageCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets LanguageCode
        /// </summary>
        [JsonPropertyName("language_code")]
        public string? LanguageCode { get { return this.LanguageCodeOption.Value; } set { this.LanguageCodeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StoreConnectionResponseProject {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  LanguageCode: ").Append(LanguageCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StoreConnectionResponseProject" />
    /// </summary>
    public partial class StoreConnectionResponseProjectJsonConverter : JsonConverter<StoreConnectionResponseProject>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="StoreConnectionResponseProjectJsonConverter" /> class.
        /// </summary>
        public StoreConnectionResponseProjectJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="StoreConnectionResponseProject" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StoreConnectionResponseProject Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<string?> domain = default;
            Option<string?> countryCode = default;
            Option<string?> languageCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "domain":
                            domain = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "country_code":
                            countryCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "language_code":
                            languageCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class StoreConnectionResponseProject.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class StoreConnectionResponseProject.", nameof(name));

            if (!domain.IsSet)
                throw new ArgumentException("Property is required for class StoreConnectionResponseProject.", nameof(domain));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class StoreConnectionResponseProject.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class StoreConnectionResponseProject.");

            if (domain.IsSet && domain.Value == null)
                throw new ArgumentNullException(nameof(domain), "Property is not nullable for class StoreConnectionResponseProject.");

            return new StoreConnectionResponseProject(id.Value!.Value!, name.Value!, domain.Value!, countryCode, languageCode);
        }

        /// <summary>
        /// Serializes a <see cref="StoreConnectionResponseProject" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="storeConnectionResponseProject"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StoreConnectionResponseProject storeConnectionResponseProject, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, storeConnectionResponseProject, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StoreConnectionResponseProject" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="storeConnectionResponseProject"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StoreConnectionResponseProject storeConnectionResponseProject, JsonSerializerOptions jsonSerializerOptions)
        {
            if (storeConnectionResponseProject.Name == null)
                throw new ArgumentNullException(nameof(storeConnectionResponseProject.Name), "Property is required for class StoreConnectionResponseProject.");

            if (storeConnectionResponseProject.Domain == null)
                throw new ArgumentNullException(nameof(storeConnectionResponseProject.Domain), "Property is required for class StoreConnectionResponseProject.");

            writer.WriteNumber("id", storeConnectionResponseProject.Id);

            writer.WriteString("name", storeConnectionResponseProject.Name);

            writer.WriteString("domain", storeConnectionResponseProject.Domain);

            if (storeConnectionResponseProject.CountryCodeOption.IsSet)
                if (storeConnectionResponseProject.CountryCodeOption.Value != null)
                    writer.WriteString("country_code", storeConnectionResponseProject.CountryCode);
                else
                    writer.WriteNull("country_code");

            if (storeConnectionResponseProject.LanguageCodeOption.IsSet)
                if (storeConnectionResponseProject.LanguageCodeOption.Value != null)
                    writer.WriteString("language_code", storeConnectionResponseProject.LanguageCode);
                else
                    writer.WriteNull("language_code");
        }
    }
}
