// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// SummaryResponseAllOfSummaryValueInner
    /// </summary>
    public partial class SummaryResponseAllOfSummaryValueInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SummaryResponseAllOfSummaryValueInner" /> class.
        /// </summary>
        /// <param name="actor">actor</param>
        /// <param name="total">total</param>
        /// <param name="min">min</param>
        /// <param name="max">max</param>
        /// <param name="last">last</param>
        [JsonConstructor]
        public SummaryResponseAllOfSummaryValueInner(Option<Actor?> actor = default, Option<decimal?> total = default, Option<decimal?> min = default, Option<decimal?> max = default, Option<decimal?> last = default)
        {
            ActorOption = actor;
            TotalOption = total;
            MinOption = min;
            MaxOption = max;
            LastOption = last;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Actor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Actor?> ActorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Actor
        /// </summary>
        [JsonPropertyName("actor")]
        public Actor? Actor { get { return this.ActorOption.Value; } set { this.ActorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Total
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TotalOption { get; private set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public decimal? Total { get { return this.TotalOption.Value; } set { this.TotalOption = new(value); } }

        /// <summary>
        /// Used to track the state of Min
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> MinOption { get; private set; }

        /// <summary>
        /// Gets or Sets Min
        /// </summary>
        [JsonPropertyName("min")]
        public decimal? Min { get { return this.MinOption.Value; } set { this.MinOption = new(value); } }

        /// <summary>
        /// Used to track the state of Max
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> MaxOption { get; private set; }

        /// <summary>
        /// Gets or Sets Max
        /// </summary>
        [JsonPropertyName("max")]
        public decimal? Max { get { return this.MaxOption.Value; } set { this.MaxOption = new(value); } }

        /// <summary>
        /// Used to track the state of Last
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> LastOption { get; private set; }

        /// <summary>
        /// Gets or Sets Last
        /// </summary>
        [JsonPropertyName("last")]
        public decimal? Last { get { return this.LastOption.Value; } set { this.LastOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SummaryResponseAllOfSummaryValueInner {\n");
            sb.Append("  Actor: ").Append(Actor).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Min: ").Append(Min).Append("\n");
            sb.Append("  Max: ").Append(Max).Append("\n");
            sb.Append("  Last: ").Append(Last).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SummaryResponseAllOfSummaryValueInner" />
    /// </summary>
    public partial class SummaryResponseAllOfSummaryValueInnerJsonConverter : JsonConverter<SummaryResponseAllOfSummaryValueInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SummaryResponseAllOfSummaryValueInnerJsonConverter" /> class.
        /// </summary>
        public SummaryResponseAllOfSummaryValueInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SummaryResponseAllOfSummaryValueInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SummaryResponseAllOfSummaryValueInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Actor?> actor = default;
            Option<decimal?> total = default;
            Option<decimal?> min = default;
            Option<decimal?> max = default;
            Option<decimal?> last = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "actor":
                            actor = new Option<Actor?>(JsonSerializer.Deserialize<Actor>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "total":
                            total = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "min":
                            min = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "max":
                            max = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "last":
                            last = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (actor.IsSet && actor.Value == null)
                throw new ArgumentNullException(nameof(actor), "Property is not nullable for class SummaryResponseAllOfSummaryValueInner.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class SummaryResponseAllOfSummaryValueInner.");

            if (min.IsSet && min.Value == null)
                throw new ArgumentNullException(nameof(min), "Property is not nullable for class SummaryResponseAllOfSummaryValueInner.");

            if (max.IsSet && max.Value == null)
                throw new ArgumentNullException(nameof(max), "Property is not nullable for class SummaryResponseAllOfSummaryValueInner.");

            if (last.IsSet && last.Value == null)
                throw new ArgumentNullException(nameof(last), "Property is not nullable for class SummaryResponseAllOfSummaryValueInner.");

            return new SummaryResponseAllOfSummaryValueInner(actor, total, min, max, last);
        }

        /// <summary>
        /// Serializes a <see cref="SummaryResponseAllOfSummaryValueInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="summaryResponseAllOfSummaryValueInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SummaryResponseAllOfSummaryValueInner summaryResponseAllOfSummaryValueInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, summaryResponseAllOfSummaryValueInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SummaryResponseAllOfSummaryValueInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="summaryResponseAllOfSummaryValueInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SummaryResponseAllOfSummaryValueInner summaryResponseAllOfSummaryValueInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (summaryResponseAllOfSummaryValueInner.ActorOption.IsSet && summaryResponseAllOfSummaryValueInner.Actor == null)
                throw new ArgumentNullException(nameof(summaryResponseAllOfSummaryValueInner.Actor), "Property is required for class SummaryResponseAllOfSummaryValueInner.");

            if (summaryResponseAllOfSummaryValueInner.ActorOption.IsSet)
            {
                writer.WritePropertyName("actor");
                JsonSerializer.Serialize(writer, summaryResponseAllOfSummaryValueInner.Actor, jsonSerializerOptions);
            }
            if (summaryResponseAllOfSummaryValueInner.TotalOption.IsSet)
                writer.WriteNumber("total", summaryResponseAllOfSummaryValueInner.TotalOption.Value!.Value);

            if (summaryResponseAllOfSummaryValueInner.MinOption.IsSet)
                writer.WriteNumber("min", summaryResponseAllOfSummaryValueInner.MinOption.Value!.Value);

            if (summaryResponseAllOfSummaryValueInner.MaxOption.IsSet)
                writer.WriteNumber("max", summaryResponseAllOfSummaryValueInner.MaxOption.Value!.Value);

            if (summaryResponseAllOfSummaryValueInner.LastOption.IsSet)
                writer.WriteNumber("last", summaryResponseAllOfSummaryValueInner.LastOption.Value!.Value);
        }
    }
}
