// <auto-generated>
/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using LLMPulse.SDK.Client;

namespace LLMPulse.SDK.Model
{
    /// <summary>
    /// UpdateProjectDraftRequest
    /// </summary>
    public partial class UpdateProjectDraftRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateProjectDraftRequest" /> class.
        /// </summary>
        /// <param name="step">step</param>
        /// <param name="name">name</param>
        /// <param name="brandName">brandName</param>
        /// <param name="description">description</param>
        /// <param name="industry">industry</param>
        /// <param name="matchingNames">matchingNames</param>
        /// <param name="externalIdentifier">externalIdentifier</param>
        /// <param name="prompts">prompts</param>
        /// <param name="competitors">competitors</param>
        /// <param name="youtubeChannelUrl">youtubeChannelUrl</param>
        /// <param name="instagramProfileUrl">instagramProfileUrl</param>
        /// <param name="facebookPageUrl">facebookPageUrl</param>
        /// <param name="tiktokProfileUrl">tiktokProfileUrl</param>
        /// <param name="appStoreUrl">appStoreUrl</param>
        /// <param name="googlePlayUrl">googlePlayUrl</param>
        /// <param name="suggest">suggest (default to true)</param>
        [JsonConstructor]
        public UpdateProjectDraftRequest(StepEnum step, Option<string?> name = default, Option<string?> brandName = default, Option<string?> description = default, Option<List<string>?> industry = default, Option<List<string>?> matchingNames = default, Option<string?> externalIdentifier = default, Option<List<string>?> prompts = default, Option<List<Object>?> competitors = default, Option<string?> youtubeChannelUrl = default, Option<string?> instagramProfileUrl = default, Option<string?> facebookPageUrl = default, Option<string?> tiktokProfileUrl = default, Option<string?> appStoreUrl = default, Option<string?> googlePlayUrl = default, Option<bool?> suggest = default)
        {
            Step = step;
            NameOption = name;
            BrandNameOption = brandName;
            DescriptionOption = description;
            IndustryOption = industry;
            MatchingNamesOption = matchingNames;
            ExternalIdentifierOption = externalIdentifier;
            PromptsOption = prompts;
            CompetitorsOption = competitors;
            YoutubeChannelUrlOption = youtubeChannelUrl;
            InstagramProfileUrlOption = instagramProfileUrl;
            FacebookPageUrlOption = facebookPageUrl;
            TiktokProfileUrlOption = tiktokProfileUrl;
            AppStoreUrlOption = appStoreUrl;
            GooglePlayUrlOption = googlePlayUrl;
            SuggestOption = suggest;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Step
        /// </summary>
        public enum StepEnum
        {
            /// <summary>
            /// Enum Details for value: details
            /// </summary>
            Details = 1,

            /// <summary>
            /// Enum Prompts for value: prompts
            /// </summary>
            Prompts = 2,

            /// <summary>
            /// Enum Competitors for value: competitors
            /// </summary>
            Competitors = 3,

            /// <summary>
            /// Enum OwnedMedia for value: owned_media
            /// </summary>
            OwnedMedia = 4
        }

        /// <summary>
        /// Returns a <see cref="StepEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StepEnum StepEnumFromString(string value)
        {
            if (value.Equals("details"))
                return StepEnum.Details;

            if (value.Equals("prompts"))
                return StepEnum.Prompts;

            if (value.Equals("competitors"))
                return StepEnum.Competitors;

            if (value.Equals("owned_media"))
                return StepEnum.OwnedMedia;

            throw new NotImplementedException($"Could not convert value to type StepEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StepEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StepEnum? StepEnumFromStringOrDefault(string value)
        {
            if (value.Equals("details"))
                return StepEnum.Details;

            if (value.Equals("prompts"))
                return StepEnum.Prompts;

            if (value.Equals("competitors"))
                return StepEnum.Competitors;

            if (value.Equals("owned_media"))
                return StepEnum.OwnedMedia;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StepEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StepEnumToJsonValue(StepEnum value)
        {
            if (value == StepEnum.Details)
                return "details";

            if (value == StepEnum.Prompts)
                return "prompts";

            if (value == StepEnum.Competitors)
                return "competitors";

            if (value == StepEnum.OwnedMedia)
                return "owned_media";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Step
        /// </summary>
        [JsonPropertyName("step")]
        public StepEnum Step { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of BrandName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BrandNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets BrandName
        /// </summary>
        [JsonPropertyName("brand_name")]
        public string? BrandName { get { return this.BrandNameOption.Value; } set { this.BrandNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Industry
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> IndustryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Industry
        /// </summary>
        [JsonPropertyName("industry")]
        public List<string>? Industry { get { return this.IndustryOption.Value; } set { this.IndustryOption = new(value); } }

        /// <summary>
        /// Used to track the state of MatchingNames
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> MatchingNamesOption { get; private set; }

        /// <summary>
        /// Gets or Sets MatchingNames
        /// </summary>
        [JsonPropertyName("matching_names")]
        public List<string>? MatchingNames { get { return this.MatchingNamesOption.Value; } set { this.MatchingNamesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalIdentifier
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdentifierOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalIdentifier
        /// </summary>
        [JsonPropertyName("external_identifier")]
        public string? ExternalIdentifier { get { return this.ExternalIdentifierOption.Value; } set { this.ExternalIdentifierOption = new(value); } }

        /// <summary>
        /// Used to track the state of Prompts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> PromptsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Prompts
        /// </summary>
        [JsonPropertyName("prompts")]
        public List<string>? Prompts { get { return this.PromptsOption.Value; } set { this.PromptsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Competitors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Object>?> CompetitorsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Competitors
        /// </summary>
        [JsonPropertyName("competitors")]
        public List<Object>? Competitors { get { return this.CompetitorsOption.Value; } set { this.CompetitorsOption = new(value); } }

        /// <summary>
        /// Used to track the state of YoutubeChannelUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> YoutubeChannelUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets YoutubeChannelUrl
        /// </summary>
        [JsonPropertyName("youtube_channel_url")]
        public string? YoutubeChannelUrl { get { return this.YoutubeChannelUrlOption.Value; } set { this.YoutubeChannelUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstagramProfileUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstagramProfileUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets InstagramProfileUrl
        /// </summary>
        [JsonPropertyName("instagram_profile_url")]
        public string? InstagramProfileUrl { get { return this.InstagramProfileUrlOption.Value; } set { this.InstagramProfileUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of FacebookPageUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FacebookPageUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets FacebookPageUrl
        /// </summary>
        [JsonPropertyName("facebook_page_url")]
        public string? FacebookPageUrl { get { return this.FacebookPageUrlOption.Value; } set { this.FacebookPageUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of TiktokProfileUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TiktokProfileUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets TiktokProfileUrl
        /// </summary>
        [JsonPropertyName("tiktok_profile_url")]
        public string? TiktokProfileUrl { get { return this.TiktokProfileUrlOption.Value; } set { this.TiktokProfileUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of AppStoreUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AppStoreUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets AppStoreUrl
        /// </summary>
        [JsonPropertyName("app_store_url")]
        public string? AppStoreUrl { get { return this.AppStoreUrlOption.Value; } set { this.AppStoreUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of GooglePlayUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GooglePlayUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets GooglePlayUrl
        /// </summary>
        [JsonPropertyName("google_play_url")]
        public string? GooglePlayUrl { get { return this.GooglePlayUrlOption.Value; } set { this.GooglePlayUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of Suggest
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SuggestOption { get; private set; }

        /// <summary>
        /// Gets or Sets Suggest
        /// </summary>
        [JsonPropertyName("suggest")]
        public bool? Suggest { get { return this.SuggestOption.Value; } set { this.SuggestOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateProjectDraftRequest {\n");
            sb.Append("  Step: ").Append(Step).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  BrandName: ").Append(BrandName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Industry: ").Append(Industry).Append("\n");
            sb.Append("  MatchingNames: ").Append(MatchingNames).Append("\n");
            sb.Append("  ExternalIdentifier: ").Append(ExternalIdentifier).Append("\n");
            sb.Append("  Prompts: ").Append(Prompts).Append("\n");
            sb.Append("  Competitors: ").Append(Competitors).Append("\n");
            sb.Append("  YoutubeChannelUrl: ").Append(YoutubeChannelUrl).Append("\n");
            sb.Append("  InstagramProfileUrl: ").Append(InstagramProfileUrl).Append("\n");
            sb.Append("  FacebookPageUrl: ").Append(FacebookPageUrl).Append("\n");
            sb.Append("  TiktokProfileUrl: ").Append(TiktokProfileUrl).Append("\n");
            sb.Append("  AppStoreUrl: ").Append(AppStoreUrl).Append("\n");
            sb.Append("  GooglePlayUrl: ").Append(GooglePlayUrl).Append("\n");
            sb.Append("  Suggest: ").Append(Suggest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateProjectDraftRequest" />
    /// </summary>
    public partial class UpdateProjectDraftRequestJsonConverter : JsonConverter<UpdateProjectDraftRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateProjectDraftRequestJsonConverter" /> class.
        /// </summary>
        public UpdateProjectDraftRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="UpdateProjectDraftRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateProjectDraftRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<UpdateProjectDraftRequest.StepEnum?> step = default;
            Option<string?> name = default;
            Option<string?> brandName = default;
            Option<string?> description = default;
            Option<List<string>?> industry = default;
            Option<List<string>?> matchingNames = default;
            Option<string?> externalIdentifier = default;
            Option<List<string>?> prompts = default;
            Option<List<Object>?> competitors = default;
            Option<string?> youtubeChannelUrl = default;
            Option<string?> instagramProfileUrl = default;
            Option<string?> facebookPageUrl = default;
            Option<string?> tiktokProfileUrl = default;
            Option<string?> appStoreUrl = default;
            Option<string?> googlePlayUrl = default;
            Option<bool?> suggest = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "step":
                            string? stepRawValue = utf8JsonReader.GetString();
                            if (stepRawValue != null)
                                step = new Option<UpdateProjectDraftRequest.StepEnum?>(UpdateProjectDraftRequest.StepEnumFromStringOrDefault(stepRawValue));
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "brand_name":
                            brandName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "industry":
                            industry = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "matching_names":
                            matchingNames = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "external_identifier":
                            externalIdentifier = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "prompts":
                            prompts = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "competitors":
                            competitors = new Option<List<Object>?>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "youtube_channel_url":
                            youtubeChannelUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "instagram_profile_url":
                            instagramProfileUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "facebook_page_url":
                            facebookPageUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tiktok_profile_url":
                            tiktokProfileUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "app_store_url":
                            appStoreUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "google_play_url":
                            googlePlayUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "suggest":
                            suggest = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!step.IsSet)
                throw new ArgumentException("Property is required for class UpdateProjectDraftRequest.", nameof(step));

            if (step.IsSet && step.Value == null)
                throw new ArgumentNullException(nameof(step), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (brandName.IsSet && brandName.Value == null)
                throw new ArgumentNullException(nameof(brandName), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (industry.IsSet && industry.Value == null)
                throw new ArgumentNullException(nameof(industry), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (matchingNames.IsSet && matchingNames.Value == null)
                throw new ArgumentNullException(nameof(matchingNames), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (externalIdentifier.IsSet && externalIdentifier.Value == null)
                throw new ArgumentNullException(nameof(externalIdentifier), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (prompts.IsSet && prompts.Value == null)
                throw new ArgumentNullException(nameof(prompts), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (competitors.IsSet && competitors.Value == null)
                throw new ArgumentNullException(nameof(competitors), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (youtubeChannelUrl.IsSet && youtubeChannelUrl.Value == null)
                throw new ArgumentNullException(nameof(youtubeChannelUrl), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (instagramProfileUrl.IsSet && instagramProfileUrl.Value == null)
                throw new ArgumentNullException(nameof(instagramProfileUrl), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (facebookPageUrl.IsSet && facebookPageUrl.Value == null)
                throw new ArgumentNullException(nameof(facebookPageUrl), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (tiktokProfileUrl.IsSet && tiktokProfileUrl.Value == null)
                throw new ArgumentNullException(nameof(tiktokProfileUrl), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (appStoreUrl.IsSet && appStoreUrl.Value == null)
                throw new ArgumentNullException(nameof(appStoreUrl), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (googlePlayUrl.IsSet && googlePlayUrl.Value == null)
                throw new ArgumentNullException(nameof(googlePlayUrl), "Property is not nullable for class UpdateProjectDraftRequest.");

            if (suggest.IsSet && suggest.Value == null)
                throw new ArgumentNullException(nameof(suggest), "Property is not nullable for class UpdateProjectDraftRequest.");

            return new UpdateProjectDraftRequest(step.Value!.Value!, name, brandName, description, industry, matchingNames, externalIdentifier, prompts, competitors, youtubeChannelUrl, instagramProfileUrl, facebookPageUrl, tiktokProfileUrl, appStoreUrl, googlePlayUrl, suggest);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateProjectDraftRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateProjectDraftRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateProjectDraftRequest updateProjectDraftRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateProjectDraftRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateProjectDraftRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateProjectDraftRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateProjectDraftRequest updateProjectDraftRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateProjectDraftRequest.NameOption.IsSet && updateProjectDraftRequest.Name == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.Name), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.BrandNameOption.IsSet && updateProjectDraftRequest.BrandName == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.BrandName), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.DescriptionOption.IsSet && updateProjectDraftRequest.Description == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.Description), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.IndustryOption.IsSet && updateProjectDraftRequest.Industry == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.Industry), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.MatchingNamesOption.IsSet && updateProjectDraftRequest.MatchingNames == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.MatchingNames), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.ExternalIdentifierOption.IsSet && updateProjectDraftRequest.ExternalIdentifier == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.ExternalIdentifier), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.PromptsOption.IsSet && updateProjectDraftRequest.Prompts == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.Prompts), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.CompetitorsOption.IsSet && updateProjectDraftRequest.Competitors == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.Competitors), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.YoutubeChannelUrlOption.IsSet && updateProjectDraftRequest.YoutubeChannelUrl == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.YoutubeChannelUrl), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.InstagramProfileUrlOption.IsSet && updateProjectDraftRequest.InstagramProfileUrl == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.InstagramProfileUrl), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.FacebookPageUrlOption.IsSet && updateProjectDraftRequest.FacebookPageUrl == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.FacebookPageUrl), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.TiktokProfileUrlOption.IsSet && updateProjectDraftRequest.TiktokProfileUrl == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.TiktokProfileUrl), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.AppStoreUrlOption.IsSet && updateProjectDraftRequest.AppStoreUrl == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.AppStoreUrl), "Property is required for class UpdateProjectDraftRequest.");

            if (updateProjectDraftRequest.GooglePlayUrlOption.IsSet && updateProjectDraftRequest.GooglePlayUrl == null)
                throw new ArgumentNullException(nameof(updateProjectDraftRequest.GooglePlayUrl), "Property is required for class UpdateProjectDraftRequest.");

            var stepRawValue = UpdateProjectDraftRequest.StepEnumToJsonValue(updateProjectDraftRequest.Step);
            writer.WriteString("step", stepRawValue);
            if (updateProjectDraftRequest.NameOption.IsSet)
                writer.WriteString("name", updateProjectDraftRequest.Name);

            if (updateProjectDraftRequest.BrandNameOption.IsSet)
                writer.WriteString("brand_name", updateProjectDraftRequest.BrandName);

            if (updateProjectDraftRequest.DescriptionOption.IsSet)
                writer.WriteString("description", updateProjectDraftRequest.Description);

            if (updateProjectDraftRequest.IndustryOption.IsSet)
            {
                writer.WritePropertyName("industry");
                JsonSerializer.Serialize(writer, updateProjectDraftRequest.Industry, jsonSerializerOptions);
            }
            if (updateProjectDraftRequest.MatchingNamesOption.IsSet)
            {
                writer.WritePropertyName("matching_names");
                JsonSerializer.Serialize(writer, updateProjectDraftRequest.MatchingNames, jsonSerializerOptions);
            }
            if (updateProjectDraftRequest.ExternalIdentifierOption.IsSet)
                writer.WriteString("external_identifier", updateProjectDraftRequest.ExternalIdentifier);

            if (updateProjectDraftRequest.PromptsOption.IsSet)
            {
                writer.WritePropertyName("prompts");
                JsonSerializer.Serialize(writer, updateProjectDraftRequest.Prompts, jsonSerializerOptions);
            }
            if (updateProjectDraftRequest.CompetitorsOption.IsSet)
            {
                writer.WritePropertyName("competitors");
                JsonSerializer.Serialize(writer, updateProjectDraftRequest.Competitors, jsonSerializerOptions);
            }
            if (updateProjectDraftRequest.YoutubeChannelUrlOption.IsSet)
                writer.WriteString("youtube_channel_url", updateProjectDraftRequest.YoutubeChannelUrl);

            if (updateProjectDraftRequest.InstagramProfileUrlOption.IsSet)
                writer.WriteString("instagram_profile_url", updateProjectDraftRequest.InstagramProfileUrl);

            if (updateProjectDraftRequest.FacebookPageUrlOption.IsSet)
                writer.WriteString("facebook_page_url", updateProjectDraftRequest.FacebookPageUrl);

            if (updateProjectDraftRequest.TiktokProfileUrlOption.IsSet)
                writer.WriteString("tiktok_profile_url", updateProjectDraftRequest.TiktokProfileUrl);

            if (updateProjectDraftRequest.AppStoreUrlOption.IsSet)
                writer.WriteString("app_store_url", updateProjectDraftRequest.AppStoreUrl);

            if (updateProjectDraftRequest.GooglePlayUrlOption.IsSet)
                writer.WriteString("google_play_url", updateProjectDraftRequest.GooglePlayUrl);

            if (updateProjectDraftRequest.SuggestOption.IsSet)
                writer.WriteBoolean("suggest", updateProjectDraftRequest.SuggestOption.Value!.Value);
        }
    }
}
